import type { SeiyuuQuizBank } from '../types';

/**
 * 青山渚（叶月恋）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/青山なぎさ
 */
export default {
  id: 'aoyama-nagisa',
  groups: ['liella'],
  intro: 'Liella! 的叶月恋。古典芭蕾练了 13 年的「独狼」，文青、红薯信徒，口癖「でやんす」。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '青山渚在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['涩谷香音', '叶月恋', '唐可可', '平安名堇'],
      answer: 1,
      explain: '她饰演结丘女子高中的学生会长叶月恋，2020 年公开招募合格后出道。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '青山渚的生日是？',
      options: ['1998 年 5 月 16 日', '2000 年 5 月 16 日', '1996 年 7 月 12 日', '2002 年 9 月 30 日'],
      answer: 0,
      explain: '1998 年 5 月 16 日生，东京都出身。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她写了 13 年的「特长」是？',
      options: ['茶道', '夜来舞', '古典芭蕾', '空手道'],
      answer: 2,
      explain: '古典芭蕾是她的特长，在 Liella! 1st Live 上还表演了本人编舞的芭蕾 solo。',
    },
    {
      id: 'q4',
      level: 'normal',
      prompt: '她几乎每天都要吃、还专门开了个「IMO 协会」节目的食物是？',
      options: ['拉面', '饺子', '香菜', '红薯'],
      answer: 3,
      explain: '红薯（IMO）是她的头号爱物，生放送《青山なぎさの勝手にIMO協会》就是红薯协会。',
    },
    {
      id: 'q5',
      level: 'easy',
      prompt: '她所属的企划组合是？',
      options: ['Liella!', 'Aqours', '虹咲学园学园偶像同好会', "μ's"],
      answer: 0,
      explain: '她是 Love Live! Superstar!! 的 Liella! 一期生成员。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她明确表示不喜欢、吃不下的食物是？',
      options: ['芹菜', '香菜', '苦瓜', '秋葵'],
      answer: 1,
      explain: '她喜欢红薯、饺子与拉面，唯独不喜欢香菜。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她读的大学是？',
      options: ['早稻田大学', '庆应义塾大学', '中央大学', '上智大学'],
      answer: 2,
      explain: '中央大学，2021 年 3 月毕业；在校期间参加过阿卡贝拉社与剧团。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她在中央大学在学期间使用过的名义是？',
      options: ['斎藤渚', '佐藤渚', '青山なぎさ', '斎藤なぎさ'],
      answer: 0,
      explain: '大学期间以「斎藤渚」的名义活动，2019 年还拿过 MISS CIRCLE CONTEST 亚军。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她长期养着的宠物是？',
      options: ['猫', '虎皮鹦鹉', '热带鱼', '仓鼠'],
      answer: 1,
      explain: '从小学四年级起养虎皮鹦鹉，到 2021 年已经养到第四代，名叫「ぽぴちゃん」。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她常挂在嘴边、后来还传染给 Liella! 全员的口癖是？',
      options: ['しょ', '〜だっちゃ', 'でやんす', 'ぽよ'],
      answer: 2,
      explain: '2021 年后她的口癖变成「でやんす」，队友也纷纷被带跑。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '她的个人生放送《青山なぎさの勝手にIMO協会》里的「IMO」指什么？',
      options: ['国际数学奥林匹克', '某个音乐企划', '她养的鹦鹉', '红薯'],
      answer: 3,
      explain: 'IMO 就是红薯，节目名直译是「青山渚的擅自红薯协会」。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她大学时期参加的两个社团是？',
      options: ['阿卡贝拉社与剧团', '轻音部与排球部', '茶道社与摄影社', '游泳队与辩论社'],
      answer: 0,
      explain: '大学加入阿卡贝拉社与剧团；轻音部（吉他）是初中，排球部是高中。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '大学前辈给她取的昵称「さいごう」是怎么来的？',
      options: ['她老家书店的名字', '萨摩芋联想到萨摩藩的西郷隆盛', '她演过的第一个角色', '她养的鹦鹉的名字'],
      answer: 1,
      explain: '因为她爱吃萨摩芋，前辈便由「萨摩」联想到萨摩藩武士西郷隆盛（さいごう）。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '2022 年她第一次以个人名义上电视，是在《めざましテレビ》的哪个环节当主持人？',
      options: ['イマドキガール', 'おはガール', 'イマドキ男子', 'お天気お姉さん'],
      answer: 0,
      explain: '2022 年 3 月底宣布担任「イマドキガール」的新年度主持人，4 月 11 日首次出演。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '关于她的出身，下列说法正确的是？',
      options: [
        '出生在北海道，小学搬到东京',
        '东京都出身，小学低年级在北海道住过两年',
        '出生在大阪，小学搬到仙台',
        '出生在福冈，一直没离开过',
      ],
      answer: 1,
      explain: '她是东京都出身，小学一到二年级因父母工作调动在北海道住过，因此偶尔会带点北海道口音。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '2019 年她参加日本大学社团选美大赛（MISS CIRCLE CONTEST）的成绩是？',
      options: ['亚军', '冠军', '季军', '入围决选但未获奖'],
      answer: 0,
      explain: '她拿到亚军，获奖访谈里说将来的梦想是成为女演员。',
    },
  ],
} satisfies SeiyuuQuizBank;
