import type { SeiyuuQuizBank } from '../types';

/**
 * 小泉萌香（三船栞子）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/小泉萌香
 */
export default {
  id: 'koizumi-moeka',
  groups: ['nijigasaki', 'revuestar'],
  intro: '三船栞子的饰演者，昵称萌 P。阿卡贝拉部 ACE、家里养着宠物蛙蚕豆。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '小泉萌香在虹咲同好会里饰演的角色是？',
      options: ['艾玛·维尔德', '三船栞子', '天王寺璃奈', '优木雪菜'],
      answer: 1,
      explain: '她饰演三船栞子，2020 年加入企划。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '小泉萌香的生日是？',
      options: ['9 月 20 日', '12 月 22 日', '2 月 27 日', '10 月 6 日'],
      answer: 2,
      explain: '1996 年 2 月 27 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '小泉萌香的出身地是？',
      options: ['静冈县', '埼玉县朝霞市', '爱知县名古屋市', '兵库县尼崎市'],
      answer: 3,
      explain: '兵库县尼崎市出身，离大阪很近，她也常在节目里聊「尼崎味」。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '虹咲里她与米娅·泰勒、钟岚珠组成的小队是？',
      options: ['R3BIRTH', 'QU4RTZ', 'DiverDiva', 'A·ZU·NA'],
      answer: 0,
      explain: '三人组成 R3BIRTH，她以三船栞子的身份在其中活动。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她在《少女☆歌剧 Revue Starlight》中饰演的角色是？',
      options: ['西条克洛迪娜', '大场奈奈', '神乐光', '石动双叶'],
      answer: 1,
      explain: '2017 年起她就在《少女☆歌剧 Revue Starlight》里饰演大场奈奈。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她是通过哪场选拔进入事务所的？',
      options: [
        '全日本国民美少女比赛',
        '事务所养成所的推荐入学',
        'Amuse Audition Festival 2014，拿下歌唱 / 声优部门大奖',
        '动漫歌曲演唱选拔',
      ],
      answer: 2,
      explain: '她大学一年级的暑假在母亲推荐下参赛并夺得大奖，当年应募人数超过三万两千人。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她在大学里最出名的身份是？',
      options: [
        '东京电机大学机械工学科的学生',
        '轻音部的主唱',
        '游泳部的队长',
        '大阪艺术大学放送学科的学生，阿卡贝拉部的 ACE',
      ],
      answer: 3,
      explain: '她读大阪艺术大学放送学科，在阿卡贝拉部是核心成员——家里也是音乐家庭，父母都毕业于该校音乐科。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她家里养的宠物是？',
      options: [
        '一只叫「蚕豆」的白氏树蛙',
        '一只叫「橡果」的猫',
        '一只叫「摩卡」的狗',
        '一缸金鱼',
      ],
      answer: 0,
      explain: '宠物蛙「蚕豆」原本是节目游戏环节里的青蛙，经工作人员同意后送给她养。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她与岩田阳葵组成的组合是？',
      options: ['R3BIRTH', 'harmoe', 'NACHERRY', 'MIX JUICE'],
      answer: 1,
      explain: '2021 年她与岩田阳葵组成 harmoe；后来还和同社的两位同事结成 MIX JUICE。',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '她有个很出名的「不喝什么」的习惯，是？',
      options: ['不喝牛奶', '不喝茶', '不喝可乐', '不喝咖啡'],
      answer: 2,
      explain: '她几乎不碰可乐（高中合唱部不允许碳酸饮料），但每天早上都喝红茶。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '她小时候的另一个梦想是？',
      options: [
        '成为职业棒球选手',
        '成为漫画家',
        '成为钢琴家',
        '成为恐龙学家，想回到恐龙时代看看',
      ],
      answer: 3,
      explain: '她非常喜欢恐龙，想当恐龙学家，特别喜欢双叶铃木龙，家里还放着模型。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她配音前有个固定习惯，是？',
      options: [
        '先吃油腻的炸鸡补充能量',
        '先喝一杯冰水',
        '先做二十分钟拉伸',
        '先唱一遍音阶',
      ],
      answer: 0,
      explain: '她会在配音前吃油腻的炸鸡；另外她得意的料理是青椒酿肉。',
    },
    {
      id: 'q13',
      level: 'normal',
      prompt: '她的姐姐从事什么工作？',
      options: ['模特（艺名リカ / Licca）', '护士', '小学老师', '钢琴老师'],
      answer: 0,
      explain: '姐姐比她大五岁，从事模特工作，艺名叫リカ（Licca）。',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '她每天早上固定会喝的是？',
      options: ['黑咖啡', '红茶（最爱玫瑰果味）', '牛奶', '绿茶'],
      answer: 1,
      explain: '受母亲影响她开始喝茶，每天早上都会喝红茶，最喜欢玫瑰果味。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '关于水族馆，下面哪个说法是对的？',
      options: ['她一年只去一次', '她从不去水族馆', '她有两张左右的水族馆年卡，被称为水族馆狂魔', '她只去动物园'],
      answer: 2,
      explain: '她常去的地方就是水族馆，手上常备两张左右的年卡。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她家里曾经住进一只野生蜘蛛，最后怎么处理的？',
      options: ['立刻打死', '扔出窗外', '装作没看见', '不忍心赶走，让它住下并取名「冒失丸」'],
      answer: 3,
      explain: '她和虫子相处不来，但看到蜘蛛努力躲藏的样子又不忍心，最后收留并取名「冒失丸」。',
    },
    {
      id: 'q17',
      level: 'hard',
      prompt: '她 0 岁就以什么身份出道，第一份工作是雅培婴儿奶粉广告？',
      options: ['婴儿模特', '电视配角', '合唱团成员', '广告旁白'],
      answer: 0,
      explain: '她 0 岁便以婴儿模特身份出道，第一份工作是婴儿奶粉广告。',
    },
    {
      id: 'q18',
      level: 'normal',
      prompt: '她配音前会吃什么来补充能量？',
      options: ['巧克力', '油腻的炸鸡', '饭团', '水果'],
      answer: 1,
      explain: '她会在配音前吃油腻的炸鸡；得意料理则是青椒酿肉。',
    },
  ],
} satisfies SeiyuuQuizBank;
