import type { SeiyuuQuizBank } from '../types';

/**
 * 岬奈子（岚千砂都）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/岬なこ
 */
export default {
  id: 'misaki-nako',
  groups: ['liella'],
  intro: 'Liella! 的岚千砂都。关西腔、会跳舞、爱做点心，出了名的「姐控」。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '岬奈子在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['涩谷香音', '岚千砂都', '叶月恋', '唐可可'],
      answer: 1,
      explain: '她饰演岚千砂都，2020 年 12 月 14 日公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '岬奈子的生日是？',
      options: ['1999 年 3 月 8 日', '1998 年 5 月 16 日', '1997 年 1 月 9 日', '2002 年 9 月 30 日'],
      answer: 0,
      explain: '1999 年 3 月 8 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她写进资料的特长是？',
      options: ['古典芭蕾', '茶道', '舞蹈', '书法'],
      answer: 2,
      explain: '特长是舞蹈，从小和姐姐一起开始学的。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她的方言是？',
      options: ['东北腔', '博多腔', '广岛腔', '关西腔'],
      answer: 3,
      explain: '她的方言是关西腔。',
    },
    {
      id: 'q5',
      level: 'easy',
      prompt: '她所属的事务所是？',
      options: ['Apollo Bay', 'Holy Peak', '青二事务所', '响 HiBiKi'],
      answer: 1,
      explain: '2019 年 4 月起成为 Holy Peak 所属新人声优，唱片公司是 Lantis。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她以「岬なこ」名义活动之前，用的是哪个名义？',
      options: ['東田岬', '東田奈子', '岬千砂', '岬なぎさ'],
      answer: 0,
      explain: '她本名東田岬（ひがしだ みさき），2019 年 4 月起以「岬なこ」的名字成为 Holy Peak 所属声优。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '以下哪一组是她的兴趣？',
      options: ['做点心、吃拉面、剪纸', '钓鱼、露营、摄影', '吉他、作词、编曲', '书法、围棋、盆栽'],
      answer: 0,
      explain: '兴趣是做点心、吃拉面与剪纸。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她最喜欢的颜色是？',
      options: ['蓝色', '黄色', '红色', '粉色'],
      answer: 1,
      explain: '她喜欢黄色，觉得明亮有朝气；小时候的双背带书包也是黄色的。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她开始学舞蹈的契机是？',
      options: ['被星探建议去学', '学校社团要求', '姐姐的朋友介绍，姐妹一起开始', '看了演唱会自己决定去报班'],
      answer: 2,
      explain: '舞蹈是经由姐姐的朋友介绍、姐妹两人一起开始的。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她中学时加入的社团，以及最终担任的职务是？',
      options: ['篮球社，当上队长', '茶道社，当上部长', '管乐社，当上首席', '排球社，当上副队长'],
      answer: 3,
      explain: '她因为姐姐在排球社而加入，姐姐退出后她坚持下来，最后当上了副队长。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她入坑 LoveLive! 的契机是？',
      options: ['看姐姐打 SIF，不知不觉比姐姐还沉迷', '朋友带她去演唱会', '电视上看到动画', '事务所安排她去试镜'],
      answer: 0,
      explain: '她是看姐姐玩 SIF 而入坑的，后来沉迷程度超过了姐姐。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她在 LoveLive! 系列里推的角色是？',
      options: ['中须霞', '艾玛·维尔德', '三船栞子', '朝香果林'],
      answer: 1,
      explain: '她推艾玛·维尔德，还被队友爆料在跨年演唱会后台一直喊着「艾玛酱」。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她在家常做的一种料理是？',
      options: ['寿喜烧', '手打乌冬', '明石烧', '烤饭团'],
      answer: 2,
      explain: '她会在家做明石烧，还觉得家家都该有一台章鱼烧机——她老家有两台。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '她的个人 solo 出道是在哪一年宣布的？',
      options: ['2021 年', '2022 年', '2024 年', '2023 年'],
      answer: 3,
      explain: '2023 年 3 月 8 日（生日当天）宣布 solo 出道，首张专辑 7 月 5 日发售。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她有一位出道前就认识的好友，同为声优，是？',
      options: ['羊宫妃那', '青木阳菜', '立石凛', '小日向美香'],
      answer: 0,
      explain: '她与羊宫妃那是出道前就认识的好友。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '在虹咲与 Liella! 的匹配环节里，她与指出毬亚达成了多少同步率并拿到第一？',
      options: ['65%', '85%', '75%', '95%'],
      answer: 1,
      explain: '两人达成 85% 同步率、位居两团第一，她本人激动到当场跪下。',
    },
  ],
} satisfies SeiyuuQuizBank;
