import type { SeiyuuQuizBank } from '../types';

/**
 * 大西亚玖璃（上原步梦）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/大西亚玖璃
 */
export default {
  id: 'ohnishi-aguri',
  groups: ['nijigasaki'],
  intro: '虹咲的立德、上原步梦的饰演者。著名哭包、家电杀手、小仓唯单推人。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '大西亚玖璃在《LoveLive!虹咲学园学园偶像同好会》中饰演的角色是？',
      options: ['朝香果林', '上原步梦', '中须霞', '樱坂雫'],
      answer: 1,
      explain: '她饰演的是同好会的立德上原步梦，也是她在虹咲企划里的起点角色。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '大西亚玖璃的生日是？',
      options: ['12 月 23 日', '4 月 17 日', '5 月 2 日', '8 月 7 日'],
      answer: 2,
      explain: '1997 年 5 月 2 日生。她在 2018 年的 21 岁生日当天开通了个人推特。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '大西亚玖璃的出身地是？',
      options: ['大阪府', '东京都', '京都府', '爱知县'],
      answer: 3,
      explain: '爱知县出身。她小时候在老家还养过兔子——「兔兔」这个名字也和兔子有缘。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '「大西亚玖璃」这个名字来源于？',
      options: ['NHK 连续电视小说《あぐり》', '她祖母的名字', '一家花店的名字', '她出生那年的台风名'],
      answer: 0,
      explain: '父母取自 NHK 连续电视小说《あぐり》的主角吉行あぐり，希望她像主角一样坚强有骨气。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '以下哪一项是大西亚玖璃写在事务所介绍里的「特技」？',
      options: ['钢琴和芭蕾', '折纸鹤、中音萨克斯管、魔方', '书法和插花', '速读和心算'],
      answer: 1,
      explain: '官方特技是折纸鹤、中音萨克斯管、魔方和「发现他人的优点」。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '大西亚玖璃是圈内知名的重度单推人，她推的声优是？',
      options: ['楠木灯', '久保田未梦', '小仓唯', '内田秀'],
      answer: 2,
      explain: '重度小仓唯单推。2019 年 ASL 后台遇到本人时直接哭了出来，被粉丝当作名场面。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '在她个人节目里和楠木灯玩魔方对决，结果如何？',
      options: [
        '两人都只复原了一面',
        '大西亚玖璃临阵放弃，主动认输',
        '两人都复原了六面，楠木灯更快',
        '大西亚玖璃复原六面，楠木灯只复原一面',
      ],
      answer: 3,
      explain: '她复原六面、灯灯复原一面，压倒性获胜——也保住了「魔方」这个特技不被划掉。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '2019 年她与大西亚玖璃、内田秀等人组成了五人声优组合，组合名是？',
      options: ['Prima Porta', 'QU4RTZ', 'DiverDiva', 'A·ZU·NA'],
      answer: 0,
      explain: '2019 年 10 月宣布与相良茉优、内田秀、高柳知叶、首藤志奈组成 Prima Porta。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '大西亚玖璃作为声优的出道作品是？',
      options: ['《多田君不恋爱》', '《新娘特别班》Drama CD', '《精灵幻想记》', '《消灭都市》'],
      answer: 1,
      explain: '2017 年在《新娘特别班》Drama CD 中饰演一之濑未羽，是她作为声优的出道作。',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '大西亚玖璃做 MBTI 测试测出的结果为？',
      options: ['ENFP-A', 'INTJ-T', 'ESFP-T', 'ISFJ-A'],
      answer: 2,
      explain: '她做完测出的是 ESFP-T（表演者人格），后来自报更新成了 INFP。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '粉丝把她列进「虹咲电器杀手」名单，下面哪件事真的发生过？',
      options: [
        '给电饭煲定时结果只煮了三分钟',
        '把吹风机放进洗衣机里一起洗',
        '把洗衣机当成了微波炉',
        '在家煮饭时忘了加水',
      ],
      answer: 3,
      explain: '她煮饭忘记加水、微波炉热带壳鸡蛋炸开、烤红薯烤焦，被粉丝列为家电苦手代表。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '在虹咲的「立德」握力测试里，大西亚玖璃的成绩是？',
      options: ['18.1，是缪水虹三团立德中最弱的', '29，排在中游', '34.8，是最强的一位', '没参加，直接弃权'],
      answer: 0,
      explain: '她握力只有 18.1（伊波杏树 29、emi 34.8），是三个团立德里最弱的，连喊「hnk 酱」都救不回来。',
    },
    {
      id: 'q13',
      level: 'normal',
      prompt: '她说话有个很容易被认出的特征，是？',
      options: ['每句话结尾都带一个明显的「嗯」尾音', '每句话都加「喵」', '说日语时总夹英语单词', '语速极快听不清楚'],
      answer: 0,
      explain: '楠木灯就是因为这个尾音，听出《精灵幻想记》ED 的演唱者是她。',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '她近年迷上了一个传统玩具，甚至在个人节目里成了固定环节，是？',
      options: ['陀螺', '剑玉', '花绳', '折纸'],
      answer: 1,
      explain: '她是十足的剑玉爱好者，口头禅是「目标是剑玉大师」。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '她 solo 出道的首张单曲是？',
      options: ['《Elder flower》', '《はじまるウェルカム》', '《本日は晴天なり》', '《ジェリーフィッシュな君へ》'],
      answer: 2,
      explain: '2021 年 3 月 3 日以《本日は晴天なり》solo 出道。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她凭哪首歌拿下了令和 3 年 Anisong 大赏新人赏？',
      options: ['《本日は晴天なり》', '《はじまるウェルカム》', '《ジェリーフィッシュな君へ》', '《Elder flower》'],
      answer: 3,
      explain: '2021 年 12 月 17 日，她凭《Elder flower》获得该奖。',
    },
    {
      id: 'q17',
      level: 'hard',
      prompt: '圈内把「虹咲团欺」当成固定节目效果，主要原因是？',
      options: [
        '她长期高强度「监视」矢野妃菜喜，于是大家乐于迫害她',
        '她总在舞台上摔倒',
        '她经常迟到被罚',
        '她怕生到不敢说话',
      ],
      answer: 0,
      explain: '她对矢野妃菜喜的占有欲太出名，久而久之「迫害兔子」就成了虹团独有的节目效果。',
    },
    {
      id: 'q18',
      level: 'normal',
      prompt: '她小时候在爱知老家养过什么宠物？',
      options: ['仓鼠', '兔子', '猫', '狗'],
      answer: 1,
      explain: '她小时候在老家养过兔子——「兔兔」这个昵称也和兔子有缘。',
    },
  ],
} satisfies SeiyuuQuizBank;
