import type { SeiyuuQuizBank } from '../types';

/**
 * 坂仓花（鬼冢冬毬）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/坂倉花
 */
export default {
  id: 'sakakura-hana',
  groups: ['liella'],
  intro: 'Liella! 三期生的坂仓花。剑道社出身、打着踢拳的爱猫家，还有一层专门放唐可可的展示柜。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '坂仓花在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['薇恩·玛格丽特', '鬼冢冬毬', '鬼冢夏美', '若菜四季'],
      answer: 1,
      explain: '她饰演三期生鬼冢冬毬，2023 年通过公开招募作为三期生声优出道。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '坂仓花的生日是？',
      options: ['2004 年 4 月 3 日', '2004 年 2 月 23 日', '2001 年 9 月 27 日', '2002 年 11 月 1 日'],
      answer: 0,
      explain: '2004 年 4 月 3 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她 2025 年 11 月起预所属的事务所是？',
      options: ['StarRise', 'Apollo Bay', 'I\u0027m Enterprise', 'Rush Style'],
      answer: 3,
      explain: '她 2025 年 10 月 31 日退出 StarRise，11 月 1 日宣布成为 Rush Style 预所属。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料的特长是？',
      options: ['游泳、和太鼓', '篮球、钢琴', '钢琴、剑道、书法', '吉他、网球、手语'],
      answer: 2,
      explain: '特长是钢琴、剑道与书法。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '以下哪一组是她的爱好？',
      options: ['篮球、唱歌', '逗猫、踢拳', '电影、跳舞', '逛面包店、卡牌游戏'],
      answer: 1,
      explain: '爱好是逗猫与踢拳；踢拳是初三时妈妈邀请她一起学的。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她家里养了几只猫？',
      options: ['三只', '一只', '两只', '五只'],
      answer: 0,
      explain: '家里有三只猫：橘猫まめ、橘白ミル和灰白色的ちー。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她家三只猫里，一收到快递就立刻钻进快递箱的是哪只？',
      options: ['まめ', 'ちー', 'ミル', '三只都会'],
      answer: 2,
      explain: 'ミル是 1 岁左右的雄性橘白，很会撒娇，喜欢钻箱子和袋子。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她喜欢的食物是？',
      options: ['蜜瓜和纳豆', '香菇和南瓜', '巧克力与鲑鱼', '生鱼片和蛋包饭'],
      answer: 3,
      explain: '她喜欢吃生鱼片和蛋包饭。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她知道 LoveLive! 系列的契机是？',
      options: ['哥哥喜欢玩 SIF', '姐姐带她看演唱会', '同学推荐动画', '事务所安排试镜'],
      answer: 0,
      explain: '从小学起就喜欢 LoveLive!，契机是哥哥玩 SIF。她是全员推，μ\u0027s 里最推小鸟。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她中学时进入剑道社的原因之一是？',
      options: ['家里开道场', '想拿全国冠军', '想找一个不需要跑步的社团', '朋友都在剑道社'],
      answer: 2,
      explain: '她受学过剑道的哥哥影响，加上想找一个不需要跑步的社团，于是进了剑道社——她自认不擅长运动，尤其讨厌跑步。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她开始练踢拳的契机是？',
      options: ['看了格斗动画', '妈妈在健身房练习后邀请她一起学', '朋友在拳馆兼职', '学校的体育课'],
      answer: 1,
      explain: '初三时妈妈在健身房练习过踢拳，之后邀请她一起学，她就此开始练踢拳。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '被问到用哪三个词形容自己时，她的回答不包括下面哪一项？',
      options: ['我行我素', '踢拳', '想法比较积极', '运动全能'],
      answer: 3,
      explain: '她的三个词是「我行我素」「踢拳」「想法比较积极」——她反而自认不擅长运动。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她房间的展示柜里，有一层专门放的是？',
      options: ['扭蛋收藏', '唐可可的周边', '猫型摆件', '书法奖状'],
      answer: 1,
      explain: '她房间展示柜里放着很多 LoveLive! 系列周边，其中有一层全是唐可可。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '她曾经在蛋糕店兼职，负责的工作是？',
      options: ['涂奶油', '烤蛋糕坯', '收银', '装饰草莓'],
      answer: 0,
      explain: '她在蛋糕店兼职负责涂奶油，因此对甜点知识有一定了解。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '在正式入选三期生之前，她自费参加了哪场演出，还在现场和岬奈子对上了视线？',
      options: ['Liella! 2nd Live 东京公演', '虹咲 5th Live', 'Liella! 3rd LoveLive! 宫城公演 Day2', 'LoveLive! 跨年演唱会'],
      answer: 2,
      explain: '她自费参加了 Liella! 3rd LoveLive! 宫城公演 Day2，期间和岬奈子对上了视线。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她有一次被粉丝津津乐道的语言小技能，是？',
      options: ['能唱粤语歌', '会用韩语打招呼', '能背日语古文', '能用中文回复 Liyuu 的帖子'],
      answer: 3,
      explain: '在长期熏陶下，她能用中文回复 Liyuu 的帖子，被粉丝调侃成「加密通话」。',
    },
  ],
} satisfies SeiyuuQuizBank;
