import type { SeiyuuQuizBank } from '../types';

/**
 * 结那（薇恩·玛格丽特）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/結那
 */
export default {
  id: 'yuina',
  groups: ['liella'],
  intro: 'Liella! 三期生的结那。会吉他、网球与手语的选美出身，甜食担当，「#结那爆食部」部长。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '结那在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['鬼冢冬毬', '薇恩·玛格丽特', '鬼冢夏美', '米女芽衣'],
      answer: 1,
      explain: '她饰演三期生薇恩·玛格丽特，2023 年 4 月 28 日正式加入 Liella!。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '结那的生日是？',
      options: ['2001 年 9 月 27 日', '2004 年 4 月 3 日', '2001 年 7 月 18 日', '2004 年 2 月 23 日'],
      answer: 0,
      explain: '2001 年 9 月 27 日生，神奈川县横滨市出身。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她的出身地是？',
      options: ['神户市', '札幌市', '横滨市', '名古屋市'],
      answer: 2,
      explain: '她出身于神奈川县横滨市。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料的特长不包括下面哪一项？',
      options: ['吉他', '网球', '手语', '剑道'],
      answer: 3,
      explain: '她的特长是吉他、网球与手语；剑道是坂仓花的特长。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她 2016 年参与组建的女子乐队名叫？',
      options: ['DROP DOLL', 'LustQueen', 'AiScReam', 'Hakoiri'],
      answer: 0,
      explain: '2016 年她与另外两人组建 DROP DOLL，负责主唱和吉他，2019 年解散。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '2021 年她在世界小姐日本大赛上获得的成绩是？',
      options: ['冠军', '准日本小姐亚军，并获多媒体综合组第一', '仅进入 TOP20', '评审特别奖（唯一奖项）'],
      answer: 1,
      explain: '2021 年她拿下准日本小姐亚军与多媒体综合组第一；2020 年作为新潟县代表进入 TOP10 并获评审特别奖。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她特地学习手语的原因是？',
      options: ['想当手语翻译', '出演的角色需要', '妹妹是先天性重度听觉失聪', '学校有手语课程'],
      answer: 2,
      explain: '她有一个小三岁的妹妹，是先天性重度听觉失聪，因此她学了手语，偶尔也会在 TikTok 发手语歌视频。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她从小开始打网球的原因是？',
      options: ['学校的社团要求', '姐姐是网球选手', '想参加全国大赛', '母亲是网球教练'],
      answer: 3,
      explain: '母亲是网球教练，所以她从很小就开始打网球。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她自认擅长做的一道料理是？',
      options: ['炒饭', '筑前煮', '白菜卷', '草莓蛋挞'],
      answer: 0,
      explain: '她擅长炒饭，而且不是颗粒分明的类型，而是软软的那种。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '关于她的饮食习惯，下列说法正确的是？',
      options: ['早饭固定吃定食', '非常爱吃甜食，早饭也常吃甜食', '完全不吃甜食', '只吃素食'],
      answer: 1,
      explain: '她喜欢草莓挞、蒙布朗这类比较瓷实的甜点，连早饭也常常是甜食，发美食内容时会用「#结那爆食部」。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她每天早上固定会做的一件事是？',
      options: ['慢跑三公里', '练一小时吉他', '早起看晨间剧', '给妹妹打视频电话'],
      answer: 2,
      explain: '她会每天早起看晨间剧。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她有一个收集爱好，是？',
      options: ['马克杯', '冰箱贴', '甜点餐具', '食物扭蛋'],
      answer: 3,
      explain: '她喜欢收集食物扭蛋。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她在节目里说过一句被粉丝当梗的名言，是？',
      options: ['「我认为太阳是从西边升起的。」', '「一天只吃三顿甜食太少了。」', '「网球比唱歌难。」', '「我从来不会紧张。」'],
      answer: 0,
      explain: '她说自己认为太阳是从西边升起的，被粉丝调侃成「九年义务教育漏网之鱼」。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '2024 年愚人节她公布自己的 MBTI 类型是？',
      options: ['ENTJ', 'HDMI', 'ISTP', 'ENFP'],
      answer: 1,
      explain: '愚人节当天她公布 MBTI 是「HDMI」（视频音频接口），连队友都吐槽让她好好诊断。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她参加 LoveLive! Superstar!! 选拔时，是带着什么状态去的？',
      options: ['刚跑完马拉松', '刚从选美决赛现场赶来', '带着舞台剧的吸血鬼妆容', '刚结束网球比赛'],
      answer: 2,
      explain: '选拔时间是从舞台剧演出的紧张日程里硬挤出来的，她只好保持着舞台剧的吸血鬼妆容直接参加。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '被绘森彩爆料，她带一个只装了一半的大行李箱去巡演，实际用途是？',
      options: ['方便当场换洗衣物', '给队友带伴手礼', '装乐器', '把 live 时叫来的食物统统打包带走'],
      answer: 3,
      explain: '宫城公演时大家普遍只带两三天行李，她却带了个空一半的大箱子，为的是打包 live 剩下的食物。',
    },
  ],
} satisfies SeiyuuQuizBank;
