import type { SeiyuuIdentity } from './types';

/**
 * 声优身份档案名册。
 *
 * 维护约定：
 * - 这是全站唯一的声优身份来源。新增玩法要用人，请从这里引用，不要另抄一份。
 * - `id` 同时是公式照文件名（`client/public/seiyuu/<id>.jpg`），改名要同步重命名图片。
 * - `name` 是站内展示用的简体中文名，`nameJa` 是官方日文表记；
 *   两者不一致时（如榆井希实 / 楡井希実）以官方表记为准放 `nameJa`。
 * - 主观印象分（气质六维等）不属于身份档案，留在各自玩法模块里按 id 关联。
 * - 改完请跑 `node scripts/verify-seiyuu.mjs` 对照服务端库与 Bangumi 复查。
 */
export const SEIYUU_ROSTER: SeiyuuIdentity[] = [
  /* ---------------- LoveLive! ---------------- */
  {
    id: 'aoyama-nagisa',
    name: '青山渚',
    nameJa: '青山なぎさ',
    romaji: 'Aoyama Nagisa',
    project: 'lovelive',
    characters: [{ name: '叶月恋', nameJa: '葉月恋', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'maeda-kaori',
    name: '前田佳织里',
    nameJa: '前田佳織里',
    romaji: 'Maeda Kaori',
    project: 'lovelive',
    characters: [{ name: '樱坂雫', nameJa: '桜坂しずく', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'kito-akari',
    name: '鬼头明里',
    nameJa: '鬼頭明里',
    romaji: 'Kito Akari',
    project: 'lovelive',
    characters: [{ name: '近江彼方', nameJa: '近江彼方', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'sashide-maria',
    name: '指出毬亚',
    nameJa: '指出毬亜',
    romaji: 'Sashide Maria',
    project: 'lovelive',
    characters: [{ name: '艾玛·维尔德', nameJa: 'エマ・ヴェルデ', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'kubota-miyu',
    name: '久保田未梦',
    nameJa: '久保田未夢',
    romaji: 'Kubota Miyu',
    project: 'lovelive',
    characters: [{ name: '朝香果林', nameJa: '朝香果林', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'tanaka-chiemi',
    name: '田中千惠美',
    nameJa: '田中ちえ美',
    romaji: 'Tanaka Chiemi',
    project: 'lovelive',
    characters: [{ name: '天王寺璃奈', nameJa: '天王寺璃奈', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'sagara-mayu',
    name: '相良茉优',
    nameJa: '相良茉優',
    romaji: 'Sagara Mayu',
    project: 'lovelive',
    characters: [{ name: '中须霞', nameJa: '中須かすみ', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'murakami-natsumi',
    name: '村上奈津实',
    nameJa: '村上奈津実',
    romaji: 'Murakami Natsumi',
    project: 'lovelive',
    characters: [{ name: '宫下爱', nameJa: '宮下愛', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'saito-shuka',
    name: '齐藤朱夏',
    nameJa: '斉藤朱夏',
    romaji: 'Saito Shuka',
    project: 'lovelive',
    characters: [{ name: '渡边曜', nameJa: '渡辺曜', work: 'LoveLive! Sunshine!!' }],
  },
  {
    id: 'aida-rikako',
    name: '逢田梨香子',
    nameJa: '逢田梨香子',
    romaji: 'Aida Rikako',
    project: 'lovelive',
    characters: [{ name: '樱内梨子', nameJa: '桜内梨子', work: 'LoveLive! Sunshine!!' }],
  },
  {
    id: 'mimori-suzuko',
    name: '三森铃子',
    nameJa: '三森すずこ',
    romaji: 'Mimori Suzuko',
    project: 'lovelive',
    alsoIn: ['revuestar', 'bangdream'],
    characters: [
      { name: '园田海未', nameJa: '園田海未', work: 'Love Live!' },
      { name: '神乐光', nameJa: '神楽ひかり', work: '少女☆歌剧 Revue Starlight' },
    ],
  },
  {
    id: 'kohara-konomi',
    name: '小原好美',
    nameJa: '小原好美',
    romaji: 'Kohara Konomi',
    project: 'lovelive',
    characters: [{ name: '大贺美沙知', nameJa: '大賀美沙知', work: '莲之空女学院学园偶像俱乐部' }],
  },
  {
    id: 'hanamiya-hina',
    name: '花宫初奈',
    nameJa: '花宮初奈',
    romaji: 'Hanamiya Hina',
    project: 'lovelive',
    characters: [{ name: '乙宗梢', nameJa: '乙宗梢', work: '莲之空女学院学园偶像俱乐部' }],
  },
  {
    id: 'date-sayuri',
    name: '伊达小百合',
    nameJa: '伊達さゆり',
    romaji: 'Date Sayuri',
    project: 'lovelive',
    characters: [{ name: '涩谷香音', nameJa: '澁谷かのん', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'liyuu',
    name: 'Liyuu',
    nameJa: 'Liyuu',
    romaji: 'Liyuu',
    project: 'lovelive',
    characters: [{ name: '唐可可', nameJa: '唐可可', work: 'Love Live! Superstar!!' }],
  },
  /* ---- Liella! 其余成员（Love Live! Superstar!!） ---- */
  {
    id: 'misaki-nako',
    name: '岬奈子',
    nameJa: '岬なこ',
    romaji: 'Misaki Nako',
    project: 'lovelive',
    characters: [{ name: '岚千砂都', nameJa: '嵐千砂都', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'payton-naomi',
    name: '佩顿尚未',
    nameJa: 'ペイトン尚未',
    romaji: 'Payton Naomi',
    project: 'lovelive',
    characters: [{ name: '平安名堇', nameJa: '平安名すみれ', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'suzuhara-nozomi',
    name: '铃原希实',
    nameJa: '鈴原希実',
    romaji: 'Suzuhara Nozomi',
    project: 'lovelive',
    characters: [{ name: '樱小路希奈子', nameJa: '桜小路きな子', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'yabushima-akane',
    name: '薮岛朱音',
    nameJa: '薮島朱音',
    romaji: 'Yabushima Akane',
    project: 'lovelive',
    characters: [{ name: '米女芽衣', nameJa: '米女メイ', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'okuma-wakana',
    name: '大熊和奏',
    nameJa: '大熊和奏',
    romaji: 'Okuma Wakana',
    project: 'lovelive',
    characters: [{ name: '若菜四季', nameJa: '若菜四季', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'emori-aya',
    name: '绘森彩',
    nameJa: '絵森彩',
    romaji: 'Emori Aya',
    project: 'lovelive',
    characters: [{ name: '鬼冢夏美', nameJa: '鬼塚夏美', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'yuina',
    name: '结那',
    nameJa: '結那',
    romaji: 'Yuina',
    project: 'lovelive',
    characters: [
      { name: '薇恩·玛格丽特', nameJa: 'ウィーン・マルガレーテ', work: 'Love Live! Superstar!!' },
    ],
  },
  {
    id: 'sakakura-hana',
    name: '坂仓花',
    nameJa: '坂倉花',
    romaji: 'Sakakura Sakura',
    project: 'lovelive',
    characters: [{ name: '鬼冢冬毬', nameJa: '鬼塚冬毬', work: 'Love Live! Superstar!!' }],
  },
  {
    id: 'ohnishi-aguri',
    name: '大西亚玖璃',
    nameJa: '大西亜玖璃',
    romaji: 'Ohnishi Aguri',
    project: 'lovelive',
    characters: [{ name: '上原步梦', nameJa: '上原歩夢', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'koizumi-moeka',
    name: '小泉萌香',
    nameJa: '小泉萌香',
    romaji: 'Koizumi Moeka',
    project: 'lovelive',
    alsoIn: ['revuestar'],
    characters: [
      { name: '三船栞子', nameJa: '三船栞子', work: '虹咲学园学园偶像同好会' },
      { name: '大场奈奈', nameJa: '大場なな', work: '少女☆歌剧 Revue Starlight' },
    ],
  },
  {
    id: 'uchida-shuu',
    name: '内田秀',
    nameJa: '内田秀',
    romaji: 'Uchida Shuu',
    project: 'lovelive',
    characters: [{ name: '米娅·泰勒', nameJa: 'ミア・テイラー', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'houmoto-akina',
    name: '法元明菜',
    nameJa: '法元明菜',
    romaji: 'Houmoto Akina',
    project: 'lovelive',
    characters: [{ name: '钟岚珠', nameJa: '鐘嵐珠', work: '虹咲学园学园偶像同好会' }],
  },
  {
    id: 'inami-anju',
    name: '伊波杏树',
    nameJa: '伊波杏樹',
    romaji: 'Inami Anju',
    project: 'lovelive',
    characters: [{ name: '高海千歌', nameJa: '高海千歌', work: 'LoveLive! Sunshine!!' }],
  },
  {
    id: 'furihata-ai',
    name: '降幡爱',
    nameJa: '降幡愛',
    romaji: 'Furihata Ai',
    project: 'lovelive',
    alsoIn: ['pjsk'],
    characters: [
      { name: '黑泽露比', nameJa: '黒澤ルビィ', work: 'LoveLive! Sunshine!!' },
      { name: '桃井爱莉', nameJa: '桃井愛莉', work: '世界计划 多彩舞台' },
    ],
  },
  {
    id: 'kusunoki-tomoyo',
    name: '楠木灯',
    nameJa: '楠木ともり',
    romaji: 'Kusunoki Tomori',
    project: 'lovelive',
    alsoIn: ['pjsk'],
    characters: [
      { name: '优木雪菜', nameJa: '優木せつ菜', work: '虹咲学园学园偶像同好会' },
      { name: '宵崎奏', nameJa: '宵崎奏', work: '世界计划 多彩舞台' },
    ],
  },
  {
    id: 'nirei-kisara',
    // 日文官方写作「楡井希実」（にれい きさら）；中文侧通行写法为「榆井希实」，
    // 站内声优库也是这个，所以 name 用中文写法、nameJa 存官方表记。
    name: '榆井希实',
    nameJa: '楡井希実',
    romaji: 'Nirei Kisara',
    project: 'lovelive',
    characters: [{ name: '日野下花帆', nameJa: '日野下花帆', work: '莲之空女学院学园偶像俱乐部' }],
  },

  /* ---------------- BanG Dream! ---------------- */
  {
    id: 'itou-ayasa',
    name: '伊藤彩沙',
    nameJa: '伊藤彩沙',
    romaji: 'Itou Ayasa',
    project: 'bangdream',
    characters: [{ name: '市谷有咲', nameJa: '市ヶ谷有咲', work: 'BanG Dream!' }],
  },
  {
    id: 'kudou-haruka',
    name: '工藤晴香',
    nameJa: '工藤晴香',
    romaji: 'Kudou Haruka',
    project: 'bangdream',
    characters: [{ name: '冰川纱夜', nameJa: '氷川紗夜', work: 'BanG Dream!' }],
  },
  {
    id: 'nakajima-yuki',
    name: '中岛由贵',
    nameJa: '中島由貴',
    romaji: 'Nakajima Yuki',
    project: 'bangdream',
    alsoIn: ['pjsk'],
    characters: [
      { name: '今井莉莎', nameJa: '今井リサ', work: 'BanG Dream!' },
      { name: '日野森志步', nameJa: '日野森志歩', work: '世界计划 多彩舞台' },
    ],
  },
  {
    id: 'sakuragawa-meggu',
    name: '樱川惠',
    nameJa: '櫻川めぐ',
    romaji: 'Sakuragawa Meggu',
    project: 'bangdream',
    characters: [{ name: '宇田川亚子', nameJa: '宇田川あこ', work: 'BanG Dream!' }],
  },
  {
    id: 'misawa-sachika',
    name: '三泽纱千香',
    nameJa: '三澤紗千香',
    romaji: 'Misawa Sachika',
    project: 'bangdream',
    alsoIn: ['umamusume'],
    characters: [
      { name: '青叶摩卡', nameJa: '青葉モカ', work: 'BanG Dream!' },
      { name: '樱花进王', nameJa: 'サクラバクシンオー', work: '赛马娘 Pretty Derby' },
    ],
  },
  {
    id: 'ozawa-ari',
    name: '小泽亚李',
    nameJa: '小澤亜李',
    romaji: 'Ozawa Ari',
    project: 'bangdream',
    characters: [{ name: '冰川日菜', nameJa: '氷川日菜', work: 'BanG Dream!' }],
  },
  {
    id: 'toyota-moe',
    name: '丰田萌绘',
    nameJa: '豊田萌絵',
    romaji: 'Toyota Moe',
    project: 'bangdream',
    characters: [{ name: '松原花音', nameJa: '松原花音', work: 'BanG Dream!' }],
  },
  {
    id: 'shindou-amane',
    name: '进藤天音',
    nameJa: '進藤あまね',
    romaji: 'Shindou Amane',
    project: 'bangdream',
    alsoIn: ['d4dj'],
    characters: [
      { name: '仓田真白', nameJa: '倉田ましろ', work: 'BanG Dream!' },
      { name: '春日春奈', nameJa: '春日春奈', work: 'D4DJ' },
    ],
  },
  {
    id: 'naota-hina',
    name: '直田姬奈',
    nameJa: '直田姫奈',
    romaji: 'Naota Hina',
    project: 'bangdream',
    characters: [{ name: '桐谷透子', nameJa: '桐ヶ谷透子', work: 'BanG Dream!' }],
  },
  {
    id: 'hayashi-koko',
    name: '林鼓子',
    nameJa: '林鼓子',
    romaji: 'Hayashi Koko',
    project: 'bangdream',
    characters: [{ name: '椎名立希', nameJa: '椎名立希', work: 'BanG Dream! It’s MyGO!!!!!' }],
  },
  {
    id: 'okada-mei',
    name: '冈田梦以',
    nameJa: '岡田夢以',
    romaji: 'Okada Mei',
    project: 'bangdream',
    alsoIn: ['d4dj'],
    characters: [
      { name: '八幡海铃', nameJa: '八幡海鈴', work: 'BanG Dream! Ave Mujica' },
      { name: '水岛茉莉花', nameJa: '水島茉莉花', work: 'D4DJ' },
    ],
  },
  {
    id: 'sasaki-riko',
    name: '佐佐木李子',
    nameJa: '佐々木李子',
    romaji: 'Sasaki Riko',
    project: 'bangdream',
    characters: [{ name: '三角初华', nameJa: '三角初華', work: 'BanG Dream! Ave Mujica' }],
  },
  {
    id: 'watase-yuzuki',
    name: '渡濑结月',
    nameJa: '渡瀬結月',
    romaji: 'Watase Yuzuki',
    project: 'bangdream',
    alsoIn: ['d4dj'],
    characters: [
      { name: '若叶睦', nameJa: '若葉睦', work: 'BanG Dream! Ave Mujica' },
      { name: '竹下美依子', nameJa: '竹下みいこ', work: 'D4DJ' },
    ],
  },
  {
    id: 'yonezawa-akane',
    name: '米泽茜',
    nameJa: '米澤茜',
    romaji: 'Yonezawa Akane',
    project: 'bangdream',
    characters: [{ name: '祐天寺若麦', nameJa: '祐天寺にゃむ', work: 'BanG Dream! Ave Mujica' }],
  },
  {
    id: 'aimi',
    name: '爱美',
    nameJa: '愛美',
    romaji: 'Aimi',
    project: 'bangdream',
    characters: [{ name: '户山香澄', nameJa: '戸山香澄', work: 'BanG Dream!' }],
  },
  {
    id: 'aiba-aina',
    name: '相羽爱奈',
    nameJa: '相羽あいな',
    romaji: 'Aiba Aina',
    project: 'bangdream',
    alsoIn: ['revuestar'],
    characters: [
      { name: '凑友希那', nameJa: '湊友希那', work: 'BanG Dream!' },
      { name: '西条克洛迪娜', nameJa: '西條クロディーヌ', work: '少女☆歌剧 Revue Starlight' },
    ],
  },
  {
    id: 'itou-miku',
    name: '伊藤美来',
    nameJa: '伊藤美来',
    romaji: 'Itou Miku',
    project: 'bangdream',
    characters: [{ name: '弦卷心', nameJa: '弦巻こころ', work: 'BanG Dream!' }],
  },
  {
    id: 'ohashi-ayaka',
    name: '大桥彩香',
    nameJa: '大橋彩香',
    romaji: 'Ohashi Ayaka',
    project: 'bangdream',
    alsoIn: ['umamusume', 'idolmaster'],
    characters: [{ name: '山吹沙绫', nameJa: '山吹沙綾', work: 'BanG Dream!' }],
  },
  {
    id: 'takao-kanon',
    name: '高尾奏音',
    nameJa: '高尾奏音',
    romaji: 'Takao Kanon',
    project: 'bangdream',
    characters: [{ name: '丰川祥子', nameJa: '豊川祥子', work: 'BanG Dream! Ave Mujica' }],
  },
  {
    id: 'hina-youmiya',
    name: '羊宫妃那',
    nameJa: '羊宮妃那',
    romaji: 'Youmiya Hina',
    project: 'bangdream',
    characters: [{ name: '高松灯', nameJa: '高松燈', work: 'BanG Dream! It’s MyGO!!!!!' }],
  },
  {
    id: 'tateishi-rin',
    name: '立石凛',
    nameJa: '立石凛',
    romaji: 'Tateishi Rin',
    project: 'bangdream',
    characters: [{ name: '千早爱音', nameJa: '千早愛音', work: 'BanG Dream! It’s MyGO!!!!!' }],
  },
  {
    id: 'aoki-hina',
    name: '青木阳菜',
    nameJa: '青木陽菜',
    romaji: 'Aoki Hina',
    project: 'bangdream',
    alsoIn: ['revuestar'],
    characters: [{ name: '要乐奈', nameJa: '要楽奈', work: 'BanG Dream! It’s MyGO!!!!!' }],
  },
  {
    id: 'kohinata-mika',
    name: '小日向美香',
    nameJa: '小日向美香',
    romaji: 'Kohinata Mika',
    project: 'bangdream',
    characters: [{ name: '长崎素世', nameJa: '長崎そよ', work: 'BanG Dream! It’s MyGO!!!!!' }],
  },

  /* ---------------- Project SEKAI ---------------- */
  {
    id: 'kino-hina',
    name: '木野日菜',
    nameJa: '木野日菜',
    romaji: 'Kino Hina',
    project: 'pjsk',
    characters: [{ name: '凤笑梦', nameJa: '鳳えむ', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'motoizumi-rina',
    name: '本泉莉奈',
    nameJa: '本泉莉奈',
    romaji: 'Motoizumi Rina',
    project: 'pjsk',
    characters: [{ name: '日野森雫', nameJa: '日野森雫', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'tanabe-rui',
    name: '田边留依',
    nameJa: '田辺留依',
    romaji: 'Tanabe Rui',
    project: 'pjsk',
    characters: [{ name: '朝比奈真冬', nameJa: '朝比奈まふゆ', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'yoshioka-mayu',
    name: '吉冈茉祐',
    nameJa: '吉岡茉祐',
    romaji: 'Yoshioka Mayu',
    project: 'pjsk',
    characters: [{ name: '桐谷遥', nameJa: '桐谷遥', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'noguchi-ruriko',
    name: '野口瑠璃子',
    nameJa: '野口瑠璃子',
    romaji: 'Noguchi Ruriko',
    project: 'pjsk',
    characters: [{ name: '星乃一歌', nameJa: '星乃一歌', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'akina',
    name: '秋奈',
    nameJa: '秋奈',
    romaji: 'Akina',
    project: 'pjsk',
    characters: [{ name: '小豆泽心羽', nameJa: '小豆沢こはね', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'isobe-karin',
    name: '礒部花凛',
    nameJa: '礒部花凜',
    romaji: 'Isobe Karin',
    project: 'pjsk',
    characters: [{ name: '天马咲希', nameJa: '天馬咲希', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'ogura-yui',
    name: '小仓唯',
    nameJa: '小倉唯',
    romaji: 'Ogura Yui',
    project: 'pjsk',
    characters: [{ name: '花里实乃里', nameJa: '花里みのり', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'suzuki-minori',
    name: '铃木实里',
    nameJa: '鈴木みのり',
    romaji: 'Suzuki Minori',
    project: 'pjsk',
    characters: [{ name: '东云绘名', nameJa: '東雲絵名', work: '世界计划 多彩舞台' }],
  },
  {
    id: 'satou-hinata',
    name: '佐藤日向',
    nameJa: '佐藤日向',
    romaji: 'Satou Hinata',
    project: 'pjsk',
    alsoIn: ['revuestar', 'd4dj'],
    characters: [
      { name: '晓山瑞希', nameJa: '暁山瑞希', work: '世界计划 多彩舞台' },
      { name: '星见纯那', nameJa: '星見純那', work: '少女☆歌剧 Revue Starlight' },
    ],
  },

  /* ---------------- 偶像大师 ---------------- */
  {
    id: 'nakamura-eriko',
    name: '中村绘里子',
    nameJa: '中村繪里子',
    romaji: 'Nakamura Eriko',
    project: 'idolmaster',
    characters: [{ name: '天海春香', nameJa: '天海春香', work: '偶像大师' }],
  },
  {
    id: 'asakura-azumi',
    name: '浅仓杏美',
    nameJa: '浅倉杏美',
    romaji: 'Asakura Azumi',
    project: 'idolmaster',
    characters: [{ name: '萩原雪步', nameJa: '萩原雪歩', work: '偶像大师' }],
  },
  {
    id: 'numakura-manami',
    name: '沼仓爱美',
    nameJa: '沼倉愛美',
    romaji: 'Numakura Manami',
    project: 'idolmaster',
    characters: [{ name: '我那霸响', nameJa: '我那覇響', work: '偶像大师' }],
  },
  {
    id: 'shimoda-asami',
    name: '下田麻美',
    nameJa: '下田麻美',
    romaji: 'Shimoda Asami',
    project: 'idolmaster',
    characters: [
      { name: '双海亚美', nameJa: '双海亜美', work: '偶像大师' },
      { name: '双海真美', nameJa: '双海真美', work: '偶像大师' },
    ],
  },
  {
    id: 'taneda-risa',
    name: '种田梨沙',
    nameJa: '種田梨沙',
    romaji: 'Taneda Risa',
    project: 'idolmaster',
    characters: [{ name: '田中琴叶', nameJa: '田中琴葉', work: '偶像大师 百万现场！' }],
  },
  {
    id: 'ootsuka-yuka',
    name: '大坪由佳',
    nameJa: '大坪由佳',
    romaji: 'Ootsubo Yuka',
    project: 'idolmaster',
    alsoIn: ['umamusume'],
    characters: [
      { name: '三村加奈子', nameJa: '三村かな子', work: '偶像大师 灰姑娘女孩' },
      { name: '大树快车', nameJa: 'タイキシャトル', work: '赛马娘 Pretty Derby' },
    ],
  },
  {
    id: 'imai-asami',
    name: '今井麻美',
    nameJa: '今井麻美',
    romaji: 'Imai Asami',
    project: 'idolmaster',
    characters: [{ name: '如月千早', nameJa: '如月千早', work: '偶像大师' }],
  },
  {
    id: 'hasegawa-akiko',
    name: '长谷川明子',
    nameJa: '長谷川明子',
    romaji: 'Hasegawa Akiko',
    project: 'idolmaster',
    characters: [{ name: '星井美希', nameJa: '星井美希', work: '偶像大师' }],
  },
  {
    id: 'hara-sayuri',
    name: '原纱友里',
    nameJa: '原紗友里',
    romaji: 'Hara Sayuri',
    project: 'idolmaster',
    characters: [{ name: '本田未央', nameJa: '本田未央', work: '偶像大师 灰姑娘女孩' }],
  },
  {
    id: 'kuroki-honoka',
    name: '黑木穗乃香',
    nameJa: '黒木ほの香',
    romaji: 'Kuroki Honoka',
    project: 'idolmaster',
    characters: [{ name: '大崎甘奈', nameJa: '大崎甘奈', work: '偶像大师 闪耀色彩' }],
  },

  /* ---------------- 学园偶像大师 ---------------- */
  {
    id: 'minato-miya',
    name: '凑美也',
    nameJa: '湊みや',
    romaji: 'Minato Miya',
    project: 'gakuen',
    characters: [{ name: '紫云清夏', nameJa: '紫雲清夏', work: '学园偶像大师' }],
  },
  {
    id: 'hanaiwa-kana',
    name: '花岩香奈',
    nameJa: '花岩香奈',
    romaji: 'Hanaiwa Kana',
    project: 'gakuen',
    characters: [{ name: '葛城莉莉娅', nameJa: '葛城リーリヤ', work: '学园偶像大师' }],
  },
  {
    id: 'usui-yuri',
    name: '薄井友里',
    nameJa: '薄井友里',
    romaji: 'Usui Yuri',
    project: 'gakuen',
    characters: [{ name: '姬崎莉波', nameJa: '姫崎莉波', work: '学园偶像大师' }],
  },
  {
    id: 'takasago-mashiro',
    name: '阳高真白',
    nameJa: '陽高真白',
    romaji: 'Takasago Mashiro',
    project: 'gakuen',
    characters: [{ name: '十王星南', nameJa: '十王星南', work: '学园偶像大师' }],
  },
  {
    id: 'nagatsuki-aoi',
    name: '长月葵',
    nameJa: '長月あおい',
    romaji: 'Nagatsuki Aoi',
    project: 'gakuen',
    characters: [{ name: '花海咲季', nameJa: '花海咲季', work: '学园偶像大师' }],
  },
  {
    id: 'koshika-nao',
    name: '小鹿奈绪',
    nameJa: '小鹿なお',
    romaji: 'Koshika Nao',
    project: 'gakuen',
    characters: [{ name: '月村手毬', nameJa: '月村手毬', work: '学园偶像大师' }],
  },
  {
    id: 'iida-hikaru',
    name: '饭田光',
    nameJa: '飯田ヒカル',
    romaji: 'Iida Hikaru',
    project: 'gakuen',
    characters: [{ name: '藤田琴音', nameJa: '藤田ことね', work: '学园偶像大师' }],
  },
  {
    id: 'kawamura-rena',
    name: '川村玲奈',
    nameJa: '川村玲奈',
    romaji: 'Kawamura Rena',
    project: 'gakuen',
    characters: [{ name: '篠泽广', nameJa: '篠澤広', work: '学园偶像大师' }],
  },

  /* ---------------- 赛马娘 ---------------- */
  {
    id: 'saitou-machico',
    name: '齐藤真知子',
    nameJa: 'Machico',
    romaji: 'Machico',
    project: 'umamusume',
    alsoIn: ['pjsk', 'idolmaster'],
    characters: [
      { name: '东海帝皇', nameJa: 'トウカイテイオー', work: '赛马娘 Pretty Derby' },
      { name: '草薙宁宁', nameJa: '草薙寧々', work: '世界计划 多彩舞台' },
    ],
  },
  {
    id: 'tadokoro-azusa',
    name: '田所梓',
    nameJa: '田所あずさ',
    romaji: 'Tadokoro Azusa',
    project: 'umamusume',
    alsoIn: ['idolmaster'],
    characters: [
      { name: '鲁道夫象征', nameJa: 'シンボリルドルフ', work: '赛马娘 Pretty Derby' },
      { name: '最上静香', nameJa: '最上静香', work: '偶像大师 百万现场！' },
    ],
  },
  {
    id: 'oozora-naomi',
    name: '大空直美',
    nameJa: '大空直美',
    romaji: 'Oozora Naomi',
    project: 'umamusume',
    characters: [{ name: '玉藻十字', nameJa: 'タマモクロス', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'tatsumi-yuiko',
    name: '巽悠衣子',
    nameJa: '巽悠衣子',
    romaji: 'Tatsumi Yuiko',
    project: 'umamusume',
    characters: [{ name: '菱亚马逊', nameJa: 'ヒシアマゾン', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'shinohara-yu',
    name: '筱原侑',
    nameJa: '篠原侑',
    romaji: 'Shinohara Yu',
    project: 'umamusume',
    characters: [{ name: '真机伶', nameJa: 'カレンチャン', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'tokui-sora',
    name: '德井青空',
    nameJa: '徳井青空',
    romaji: 'Tokui Sora',
    project: 'umamusume',
    alsoIn: ['lovelive'],
    characters: [
      { name: '竹正歌剧王', nameJa: 'テイエムオペラオー', work: '赛马娘 Pretty Derby' },
      { name: '矢泽日香', nameJa: '矢澤にこ', work: 'Love Live!' },
    ],
  },
  {
    id: 'waki-azumi',
    name: '和气杏未',
    nameJa: '和氣あず未',
    romaji: 'Waki Azumi',
    project: 'umamusume',
    alsoIn: ['lovelive'],
    characters: [{ name: '特别周', nameJa: 'スペシャルウィーク', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'takano-marika',
    name: '高野麻里佳',
    nameJa: '高野麻里佳',
    romaji: 'Takano Marika',
    project: 'umamusume',
    characters: [{ name: '无声铃鹿', nameJa: 'サイレンススズカ', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'ueda-hitomi',
    name: '上田瞳',
    nameJa: '上田瞳',
    romaji: 'Ueda Hitomi',
    project: 'umamusume',
    characters: [{ name: '黄金船', nameJa: 'ゴールドシップ', work: '赛马娘 Pretty Derby' }],
  },
  {
    id: 'yano-hinaki',
    name: '矢野妃菜喜',
    nameJa: '矢野妃菜喜',
    romaji: 'Yano Hinaki',
    project: 'umamusume',
    alsoIn: ['lovelive'],
    characters: [
      { name: '北部玄驹', nameJa: 'キタサンブラック', work: '赛马娘 Pretty Derby' },
      { name: '高咲侑', nameJa: '高咲侑', work: '虹咲学园学园偶像同好会' },
    ],
  },

  /* ---------------- 少女☆歌剧 Revue Starlight ---------------- */
  {
    id: 'ikuta-teru',
    name: '生田辉',
    nameJa: '生田輝',
    romaji: 'Ikuta Teru',
    project: 'revuestar',
    characters: [{ name: '石动双叶', nameJa: '石動双葉', work: '少女☆歌剧 Revue Starlight' }],
  },
  {
    id: 'koyama-momoyo',
    name: '小山百代',
    nameJa: '小山百代',
    romaji: 'Koyama Momoyo',
    project: 'revuestar',
    characters: [{ name: '爱城华恋', nameJa: '愛城華恋', work: '少女☆歌剧 Revue Starlight' }],
  },
  {
    id: 'iwata-haruki',
    name: '岩田阳葵',
    nameJa: '岩田陽葵',
    romaji: 'Iwata Haruki',
    project: 'revuestar',
    alsoIn: ['d4dj'],
    characters: [{ name: '露崎真昼', nameJa: '露崎まひる', work: '少女☆歌剧 Revue Starlight' }],
  },
  {
    id: 'tomita-maho',
    name: '富田麻帆',
    nameJa: '富田麻帆',
    romaji: 'Tomita Maho',
    project: 'revuestar',
    characters: [{ name: '天堂真矢', nameJa: '天堂真矢', work: '少女☆歌剧 Revue Starlight' }],
  },

  /* ---------------- D4DJ ---------------- */
  {
    id: 'kurahashi-rei',
    name: '仓知玲凤',
    nameJa: '倉知玲鳳',
    romaji: 'Kurahashi Rei',
    project: 'd4dj',
    alsoIn: ['bangdream'],
    characters: [
      { name: '清水绘空', nameJa: '清水絵空', work: 'D4DJ' },
      { name: '鳰原令王那', nameJa: '鳰原令王那', work: 'BanG Dream!' },
    ],
  },
  {
    id: 'takagi-miyu',
    name: '高木美佑',
    nameJa: '高木美佑',
    romaji: 'Takagi Miyu',
    project: 'd4dj',
    characters: [{ name: '犬寄忍', nameJa: '犬寄しのぶ', work: 'D4DJ' }],
  },
  {
    id: 'kozaki-kanon',
    name: '志崎桦音',
    nameJa: '志崎樺音',
    romaji: 'Kozaki Kanon',
    project: 'd4dj',
    characters: [{ name: '渡月丽', nameJa: '渡月麗', work: 'D4DJ' }],
  },
  {
    id: 'ootsuka-sae',
    name: '大冢纱英',
    nameJa: '大塚紗英',
    romaji: 'Ootsuka Sae',
    project: 'd4dj',
    alsoIn: ['bangdream'],
    characters: [
      { name: '月见山渚', nameJa: '月見山渚', work: 'D4DJ' },
      { name: '花园多惠', nameJa: '花園たえ', work: 'BanG Dream!' },
    ],
  },
  {
    id: 'nishio-yuka',
    name: '西尾夕香',
    nameJa: '西尾夕香',
    romaji: 'Nishio Yuka',
    project: 'd4dj',
    alsoIn: ['bangdream'],
    characters: [
      { name: '爱本铃久', nameJa: '愛本りんく', work: 'D4DJ' },
      { name: '广町七深', nameJa: '広町七深', work: 'BanG Dream!' },
    ],
  },
  {
    id: 'tsumugi-risa',
    name: '纺木吏佐',
    nameJa: '紡木吏佐',
    romaji: 'Tsumugi Risa',
    project: 'd4dj',
    alsoIn: ['bangdream'],
    characters: [
      { name: '出云咲姬', nameJa: '出雲咲姫', work: 'D4DJ' },
      { name: '珠手知由', nameJa: '珠手ちゆ', work: 'BanG Dream!' },
    ],
  },
];
