import type { SeiyuuQuizBank } from '../types';

/**
 * 伊达小百合（涩谷香音）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/伊達さゆり
 */
export default {
  id: 'date-sayuri',
  groups: ['liella'],
  intro: 'Liella! 的涩谷香音。夜来舞与茶道部的履历、150cm 的「打铁匠」，游戏运气极差的立德。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '伊达小百合在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['叶月恋', '涩谷香音', '平安名堇', '岚千砂都'],
      answer: 1,
      explain: '她饰演 Liella! 的立德涩谷香音，2020 年公开招募合格后出道。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '伊达小百合的生日是？',
      options: ['2002 年 9 月 30 日', '1998 年 5 月 16 日', '1997 年 1 月 9 日', '2000 年 12 月 22 日'],
      answer: 0,
      explain: '2002 年 9 月 30 日生，宫城县仙台市出身。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她的身高是？',
      options: ['160.0cm', '155.0cm', '150.0cm', '145.0cm'],
      answer: 2,
      explain: '2023 年体检量出的精确身高是 150.0cm，Liella! 11 人里最矮。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料的特技是？',
      options: ['茶道', '古典芭蕾', '钢琴', '夜来舞'],
      answer: 3,
      explain: '特技是夜来舞，初中社团三年跳下来的，本人都说「不知道能不能算特技」。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她高中时加入的社团是？',
      options: ['茶道部', '轻音部', '排球部', '阿卡贝拉社'],
      answer: 0,
      explain: '高中加入茶道部，一周活动两次；她自己也说茶道的礼仪很难。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她有一位同样在演艺圈工作的亲属，是？',
      options: ['父亲', '哥哥', '伯父', '表姐'],
      answer: 2,
      explain: '她的伯父是伊达干生。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她的个人广播在 2022 年拿过哪个奖？',
      options: ['BEST CUTE RADIO 最可爱广播奖', '最佳新人广播奖', '年度最佳综艺广播奖', '最佳深夜广播奖'],
      answer: 0,
      explain: '《伊達さゆりの伊達ちゃんは伊達じゃない！！！》拿下第 7 届动漫广播大赏的 BEST CUTE RADIO 最可爱广播奖。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她在 niconico 的个人频道名字里，说想再长高多少？',
      options: ['3 厘米', '5 厘米', '10 厘米', '8 厘米'],
      answer: 3,
      explain: '频道名叫「伊达小百合的还可以再长高 8 厘米！」。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她的 1st 写真集名叫？',
      options: ['《足迹》', '《转身》', '《第一天》', '《休息日》'],
      answer: 0,
      explain: '1st 写真集《足迹》于 2022 年 9 月 28 日发售，正赶上 20 岁生日。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她自嘲抽卡运气极差，最经典的一次是？',
      options: ['十连开出两张 UR', '单抽连出三张 UR', '十连抽满 SR', '用 50 颗 Loveca 的 11 连抽全是 R'],
      answer: 3,
      explain: '她自己讲过：攒了 50 颗 Loveca 做 11 连，结果全是 R，连 SR 都没见到。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '被问宫城县推荐美食时，她推荐的是什么？',
      options: ['仙城芹菜火锅', '仙台牛舌', '白石温面', '毛豆泥麻糬'],
      answer: 0,
      explain: '她推荐仙城的芹菜火锅（せり鍋），理由是芹菜味被煮得很淡，不爱吃芹菜的人也能接受。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她有个绰号叫「播放键leader」，原因是？',
      options: [
        '她演的节目开场总由她按播放键',
        '视频封面的播放键经常正好挡住她的脑袋',
        '她说过自己只想当「播放键」',
        '她的应援色跟播放键一样',
      ],
      answer: 1,
      explain: '她在推文、YouTube、niconico 的封面常站 C 位，而播放键往往正正好好挡住她的头。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她说自己不常说真正的宫城腔，但有一个词会不自觉带出来，是？',
      options: ['けっぱる', 'おはようさん', 'いずい', '〜だっちゃ'],
      answer: 2,
      explain: '她会不自觉说「いずい」，而「〜だっちゃ」这种真正的宫城方言反而不会说。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '2021 年她担任了广播节目「ラジオどっとあい」第几代主持人？',
      options: ['第 79 代', '第 91 代', '第 100 代', '第 87 代'],
      answer: 3,
      explain: '她是第 87 代主持人，副标题是「伊達さゆりの伊達ちゃんは伊達じゃない！！！」。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '和大西亚玖璃拍广告时，因为身高差太大而出现的对策是？',
      options: ['让她站在台子上', '改成坐着拍', '只拍上半身', '用远景虚化身高差'],
      answer: 0,
      explain: '因为身高差太大，她不得不踩台子，于是有了「打铁台」这个说法。',
    },
  ],
} satisfies SeiyuuQuizBank;
