import type { SeiyuuQuizBank } from '../types';

/**
 * 绘森彩（鬼冢夏美）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/絵森彩
 */
export default {
  id: 'emori-aya',
  groups: ['liella'],
  intro: 'Liella! 二期生的绘森彩。篮球部出身、能做草莓蛋挞的理科女，乃木坂 46 的忠实粉丝。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '绘森彩在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['米女芽衣', '鬼冢夏美', '若菜四季', '樱小路希奈子'],
      answer: 1,
      explain: '她饰演二期生鬼冢夏美，2022 年 5 月 12 日作为 Liella! 2 期生公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '绘森彩的生日是？',
      options: ['2004 年 2 月 23 日', '2004 年 4 月 3 日', '2001 年 9 月 27 日', '2002 年 11 月 1 日'],
      answer: 0,
      explain: '2004 年 2 月 23 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她所属的事务所是？',
      options: ['Apollo Bay', '贤Production', 'Holy Peak', 'BOX CORPORATION'],
      answer: 3,
      explain: '她 2021 年上半年加入 BOX CORPORATION。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料的特长不包括下面哪一项？',
      options: ['篮球', '钢琴', '音游', '剑道'],
      answer: 3,
      explain: '她的特长是篮球、钢琴与音游；剑道是坂仓花的特长。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她在改名为「绘森彩」之前使用的艺名是？',
      options: ['依田彩花', '依田彩', '绘森依花', '依田花'],
      answer: 0,
      explain: '她 2013 年以「依田彩花」作为童星出道，2019 年还加入过地下偶像团体，2021 年 9 月改名为绘森彩。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '2021 年她参加过哪个大型偶像团体的五期生选拔（最终被淘汰）？',
      options: ['樱坂 46', '乃木坂 46', '日向坂 46', 'AKB48'],
      answer: 1,
      explain: '她参加乃木坂 46 五期生选拔落选，之后加入 BOX CORPORATION；她本人也是乃木坂 46 的粉丝。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她高中时属于哪个社团？',
      options: ['剑道社', '轻音部', '篮球部', '茶道社'],
      answer: 2,
      explain: '她高中是篮球部队员，平时也常看日本 B 联赛。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她最喜欢的冰淇淋口味是？',
      options: ['抹茶', '香草', '草莓', '葡萄干朗姆酒'],
      answer: 3,
      explain: '她小时候觉得不好吃、长大后却非常喜欢的是葡萄干朗姆酒冰淇淋。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她不喜欢吃的食物是？',
      options: ['香菇', '秋葵', '纳豆', '芹菜'],
      answer: 0,
      explain: '她不吃香菇和有动物腥味的肉，也不太对付鲜奶油蛋糕（所以圣诞都买芝士蛋糕）。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她自认擅长做的一道料理是？',
      options: ['筑前煮', '白菜卷', '韩式胡萝卜煎饼', '炒蛋'],
      answer: 0,
      explain: '她擅长筑前煮，做料理几乎没被菜刀切到过手。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她在甜点方面的拿手项目是？',
      options: ['烤芝士蛋糕', '烤戚风蛋糕', '从面坯开始做草莓蛋挞', '做奶油泡芙'],
      answer: 2,
      explain: '她能从头做草莓蛋挞，连牛奶蛋糊、杏仁奶油都自己做。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她在 μ\u0027s 里推的角色是？',
      options: ['西木野真姬', '南小鸟', '园田海未', '东条希'],
      answer: 3,
      explain: '她 μ\u0027s 推东条希，2014 年前后就通过 SIF 了解到 LoveLive!，本人还是个 SIF 高手。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她老家的小狗「なっつ」名字来自哪里？',
      options: ['幼儿园时在《光之美少女》里看到的妖精', '她喜欢的甜点', '老家院子里的树', '前辈声优的角色名'],
      answer: 0,
      explain: '名字取自她幼儿园时看的《光之美少女》里的妖精，昵称「なっちゃん」。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '她 2022 年 11 月开设的个人直播频道名叫？',
      options: ['《エモリアルCafe》', '《彩的房间》', '《Aya Channel》', '《绘森商店》'],
      answer: 0,
      explain: '2022 年 11 月 22 日开设个人直播频道《絵森彩のエモリアルCafe》，2023 年 4 月又开设了官方 Fan Club。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她 2024 年 4 月起以哪个名义开展艺人活动？',
      options: ['LustQueen', 'Spileben', 'Aya Emori', 'Emorin'],
      answer: 2,
      explain: '2024 年 4 月 1 日宣布以「Aya Emori」名义在 Bandai Namco Music Live 旗下 StarRise 开展艺人活动。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她在学校的偏科情况是？',
      options: ['文科强、理科弱', '全都一样', '体育强、文化课弱', '理科强，喜欢数学和化学'],
      answer: 3,
      explain: '她算是理科女，喜欢数学和化学，对需要大量背诵的社会学、历史相对不擅长。',
    },
  ],
} satisfies SeiyuuQuizBank;
