import type { SeiyuuQuizBank } from '../types';

/**
 * 林鼓子（优木雪菜 / 椎名立希）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/林鼓子
 *
 * 少见的同时坐拥 LoveLive! 与 BanG Dream! 两个企划主役的人，
 * 所以这里同时归入虹咲与 MyGO!!!!! 两组。
 */
export default {
  id: 'hayashi-koko',
  groups: ['nijigasaki', 'mygo'],
  intro: '二代目优木雪菜、MyGO!!!!! 的鼓手椎名立希。真正的「拉邦结派」之人。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '林鼓子在《LoveLive!虹咲学园学园偶像同好会》里饰演的角色是？',
      options: ['上原步梦', '优木雪菜', '三船栞子', '钟岚珠'],
      answer: 1,
      explain: '她于 2023 年 4 月 1 日起接替卸任的楠木灯，饰演优木雪菜。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '她在 BanG Dream! 的 MyGO!!!!! 里担任的角色与位置是？',
      options: ['贝斯手长崎爽世', '主唱高松灯', '鼓手椎名立希', '吉他手千早爱音'],
      answer: 2,
      explain: '她是 MyGO!!!!! 的鼓手椎名立希，2023 年 4 月 9 日正式公布。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '林鼓子的生日是？',
      options: ['2000 年 3 月 14 日', '1997 年 3 月 5 日', '2001 年 8 月 17 日', '2002 年 5 月 15 日'],
      answer: 3,
      explain: '2002 年 5 月 15 日生，她的个人 Nico 频道第一期就选在生日开播。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '林鼓子的出身地是？',
      options: ['静冈县滨松市', '千叶县南房总市', '爱知县名古屋市', '埼玉县朝霞市'],
      answer: 0,
      explain: '静冈县滨松市出身，会讲远州弁。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她在声优圈里有个「第一」的头衔，是？',
      options: [
        '首位在红白歌会登场的 00 后声优',
        '首位同时担任 LoveLive! 系列与 BanG Dream! 系列主役的声优',
        '首位在动画中同时配 11 个角色的声优',
        '首位获得声优奖主演女优赏的 00 后',
      ],
      answer: 1,
      explain: '她同时是虹咲的优木雪菜与 MyGO!!!!! 的椎名立希，是两大人气企划的主役，被粉丝称为「拉邦结派」。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她 2017 年通过《Wake Up, Girls!》的试镜后，与其他两人组成的声优组合是？',
      options: ['i☆Ris', 'Prima Porta', 'Run Girls, Run!', 'harmoe'],
      answer: 2,
      explain: '她与森岛优花、厚木那奈美组成 Run Girls, Run!，该组合于 2023 年 3 月的 Final Live 后停止活动。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她首次担任主役的作品和角色是？',
      options: [
        '《Wake Up, Girls! 新章》的速志步',
        '《LoveLive!虹咲学园学园偶像同好会》的优木雪菜',
        '《BanG Dream!》的椎名立希',
        '《美妙☆频道》的桃山未来',
      ],
      answer: 3,
      explain: '2018 年她在《美妙☆频道》饰演桃山未来，首次担纲主役。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她在 2019 年获得的奖项是？',
      options: ['第 13 届声优奖新人女优赏', '第 15 届声优奖助演女优赏', '第 17 届声优奖歌唱奖', '第 10 届声优奖主演女优赏'],
      answer: 0,
      explain: '2019 年（第 13 届）声优奖，她拿到新人女优赏。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '以下哪一组是林鼓子的「特技」？',
      options: ['小提琴与长笛', '鼓、各种打击乐、钢琴', '珠算与飞镖', '水肺潜水与叉车'],
      answer: 1,
      explain: '特技是鼓、各种打击乐和钢琴；兴趣是插画和看音乐剧。',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '她之所以走上打击乐之路，起因是？',
      options: [
        '哥哥是鼓手，家里就有一套鼓',
        '乐队临时缺鼓手，她被拉去救场',
        '小学进铜管乐队时管乐器都吹不响，只能去负责打击乐',
        '参加选拔时被评委指定去打鼓',
      ],
      answer: 2,
      explain: '她小学加入铜管乐队，管乐器怎么都吹不响，于是被安排去负责打击乐，初中也顺势进了吹奏乐部。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '关于她的视力，下面哪个说法是对的？',
      options: ['裸眼 1.5 以上，从不戴眼镜', '两眼都是 1.2', '只有左眼近视', '裸眼视力只有 0.04，超级散光'],
      answer: 3,
      explain: '她散光严重、裸眼视力仅 0.04，必须戴眼镜或隐形眼镜。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她在《LoveLive!Sunshine!!》剧场版里配过一个龙套，这段经历后来成了名场面，原因是？',
      options: [
        '那句台词是「我上高中之后绝对要加入学园偶像部」，四年后她真的接了优木雪菜',
        '她给南小鸟配过替补音',
        '她给椎名立希配过幼年音',
        '那是她人生第一次试镜就中选的主役',
      ],
      answer: 0,
      explain: '2019 年剧场版里她配的龙套说了「我上高中之后绝对要加入学园偶像部」，2023 年她真的成为了虹咲的学园偶像声优。',
    },
    {
      id: 'q13',
      level: 'normal',
      prompt: '她 11 岁成为声优爱好者的契机是？',
      options: ['和爸爸一起看了《LoveLive!》动画', '在电视上看到《美妙☆频道》', '被朋友带去看音乐剧', '在 YouTube 上刷到 μ\'s 的 Live'],
      answer: 0,
      explain: '她 11 岁时和爸爸一起看《LoveLive!》动画，从此喜欢上声优，也推南小鸟、小泉花阳。',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '她的昵称「林丸（はやまる）」是怎么来的？',
      options: ['粉丝投票选出', '出道时由身为德井青空粉丝的爸爸取的（姓 + 空丸的丸）', '来自动画角色的名字', '是经纪人的创意'],
      answer: 1,
      explain: '「林丸」是爸爸取的爱称，她自己也是知名的空丸厨。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '她母亲从事的职业是？',
      options: ['护士', '公司职员', '钢琴老师', '料理老师'],
      answer: 2,
      explain: '母亲是钢琴老师，认为音调感很重要，所以让她 5 岁就开始学唱歌。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她初中加入吹奏乐部的契机是？',
      options: ['姐姐在吹奏部，跟着进去了', '被老师推荐去当打击乐手', '学校规定每人必须参加一个社团', '看了《吹响！上低音号》，觉得这是命运，于是加入吹奏部'],
      answer: 3,
      explain: '她初一时正好《吹响！上低音号》开播，觉得这是命运便加入了吹奏部，动画里的课题曲也是她们演奏会的曲目。',
    },
    {
      id: 'q17',
      level: 'hard',
      prompt: '她长期使用的架子鼓品牌是？',
      options: ['Pearl（珍珠）', 'Yamaha', 'Tama', 'Ludwig'],
      answer: 0,
      explain: '她从学生时代起一直用 Pearl 的鼓，出演椎名立希后用的是 Masters Maple Gum 鼓组。',
    },
    {
      id: 'q18',
      level: 'hard',
      prompt: '2023 年 12 月异次元 Fes 上发生了一个有名的放送事故，是？',
      options: ['她的鼓突然断了', '导播错误地把大西亚玖璃的画面给了林鼓子', '她忘记了自我介绍', '因为调音问题整首歌重唱'],
      answer: 1,
      explain: '表演《追梦跑路人》时，导播把大西亚玖璃的画面切给了林鼓子，成了名场面。',
    },
  ],
} satisfies SeiyuuQuizBank;
