import type { SeiyuuQuizBank } from '../types';

/**
 * 久保田未梦（朝香果林）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/久保田未梦
 */
export default {
  id: 'kubota-miyu',
  groups: ['nijigasaki'],
  intro: '朝香果林的饰演者，i☆Ris 成员。工科出身、持叉车执照、潜水爱好者的反差担当。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '久保田未梦在虹咲同好会里饰演的角色是？',
      options: ['天王寺璃奈', '朝香果林', '近江彼方', '艾玛·维尔德'],
      answer: 1,
      explain: '她饰演朝香果林。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '久保田未梦的生日是？',
      options: ['7 月 7 日', '10 月 21 日', '1 月 31 日', '3 月 14 日'],
      answer: 2,
      explain: '1995 年 1 月 31 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '久保田未梦的出身地是？',
      options: ['福冈县北九州市', '京都府', '北海道札幌市', '埼玉县秩父市'],
      answer: 3,
      explain: '埼玉县秩父市出身，本人也常自称「乡下」。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '久保田未梦除虹咲之外，还是哪个偶像组合的成员？',
      options: ['i☆Ris', 'Prima Porta', 'SPR5', 'A·ZU·NA'],
      answer: 0,
      explain: '她是 i☆Ris 成员，应援色为橙色；2016 年曾以 i☆Ris 名义拿下声优奖歌唱奖。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '久保田未梦读大学时选的学科是？',
      options: [
        '日本大学艺术学部',
        '东京电机大学理工部机械工学科',
        '早稻田大学文学部',
        '多摩美术大学设计学科',
      ],
      answer: 1,
      explain: '她从小玩电脑、初中做过网站，对程序设计有兴趣，于是升入工科高中，后来进了东京电机大学理工部机械工学科。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '以下哪一项是久保田未梦的「特技」？',
      options: ['剑道、空手道、柔道', '书法、茶道、花道', '水肺潜水、叉车、电弧焊', '钢琴、声乐、芭蕾'],
      answer: 2,
      explain: '她的特技是水肺潜水、叉车、电弧焊，还有肉类鉴定 2 级。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她首次担任主役的作品和角色是？',
      options: [
        '《潜行吧！奈亚子W》的店员',
        '《格林笔记》的诗音',
        '《邪神与厨二病少女》的美杜莎',
        '《美妙天堂》的北条索菲',
      ],
      answer: 3,
      explain: '她首次担纲主役是 2014 年《美妙天堂》的北条索菲（★出道作是 2013 年《潜行吧！奈亚子W》的店员）。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '久保田未梦在饮食上有个很有名的特点，是？',
      options: [
        '非常讨厌蔬菜，直到 20 岁才知道蔬菜的味道',
        '非常讨厌甜食，从不吃蛋糕',
        '无辣不欢，什么都要加辣椒',
        '只吃自己做的便当',
      ],
      answer: 0,
      explain: '她讨厌蔬菜（20 岁才知道蔬菜的味道），还讨厌青蛙，曾在节目上说过希望青蛙灭绝。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她家里那条「写着名字的网线」是怎么回事？',
      options: [
        '是她在电器店抽奖抽到的',
        '是高中时的作业，她自己做的，上面写着「久保田」',
        '是粉丝送的礼物，她一直留着',
        '是 i☆Ris 的周边商品',
      ],
      answer: 1,
      explain: '那条网线是她高中时的作业，自制并写上了「久保田」，成了她工科出身的名物证。',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '她高中时期发生过的意外是？',
      options: [
        '把学校的电脑弄坏了被迫赔钱',
        '练习焊接时烧穿了校服',
        '用烙铁时不小心点燃了头发',
        '在实验室里被电弧焊烫伤了手',
      ],
      answer: 2,
      explain: '她高中时曾不慎用烙铁点燃过自己的头发。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: 'i☆Ris 13 周年演唱会彩排时，她不小心做了什么？',
      options: [
        '把自己的演出服弄丢了',
        '误删了演唱会的曲目单',
        '把彩排的录像全部覆盖了',
        '把 i☆Ris 群组 10 年的聊天记录删掉了',
      ],
      answer: 3,
      explain: '她在彩排时因为太累，不小心删掉了 i☆Ris 群组 10 年的聊天记录。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她的第一本写真集《未夢-みゆ-》是在哪里拍摄的？',
      options: ['菲律宾宿雾', '澳大利亚珀斯', '冲绳', '关岛'],
      answer: 0,
      explain: '她向事务所提出想去热带海岛拍，最后选了菲律宾宿雾；她原本还曾考虑去珀斯留学当潜水员。',
    },
    {
      id: 'q13',
      level: 'normal',
      prompt: '她讨厌到公开表示希望它灭绝的动物是？',
      options: ['青蛙', '蟑螂', '蜘蛛', '蛇'],
      answer: 0,
      explain: '她讨厌青蛙，曾在节目里说过希望青蛙灭绝。',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '她不擅长做哪种 wink？',
      options: ['左眼', '右眼', '两只都不行', '两只都很擅长'],
      answer: 1,
      explain: '她不擅长右眼 wink——这一点和大西亚玖璃一样。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '她在 i☆Ris 中的应援色是？',
      options: ['蓝色', '粉色', '橙色', '紫色'],
      answer: 2,
      explain: '她的应援色是橙色。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '如果当年没通过 i☆Ris 的选拔，她原本打算去做什么？',
      options: ['回老家开店', '考公务员', '去美国留学', '去澳大利亚当潜水员（甚至考虑过珀斯留学）'],
      answer: 3,
      explain: '她本来想从事和海有关的工作，收集信息时才参选 i☆Ris。',
    },
    {
      id: 'q17',
      level: 'normal',
      prompt: '她非常敬佩、教会她很多东西的同事务所前辈是？',
      options: ['德井青空', '水树奈奈', '田村由香里', '竹达彩奈'],
      answer: 0,
      explain: '她刚出道时受德井青空照顾很多，后来总会跑到前辈身边直球表达喜欢。',
    },
    {
      id: 'q18',
      level: 'hard',
      prompt: '大学时期忙于 i☆Ris 活动，她曾在哪里练习《美妙天堂》的舞蹈？',
      options: ['车站月台', '大学厕所里', '家里阳台', '公园长椅'],
      answer: 1,
      explain: '为了抢时间，她曾在校内厕所里练《美妙天堂》的舞蹈。',
    },
  ],
} satisfies SeiyuuQuizBank;
