import type { SeiyuuQuizBank } from '../types';

/**
 * Liyuu（唐可可）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/Liyuu
 */
export default {
  id: 'liyuu',
  groups: ['liella'],
  intro: 'Liella! 的唐可可。来自上海的画手兼歌手，LL 系列第一位外国人主役，169cm 的「鲤鱼王」。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: 'Liyuu 在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['叶月恋', '涩谷香音', '唐可可', '平安名堇'],
      answer: 2,
      explain: '她饰演来自上海的唐可可，2020 年 12 月公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: 'Liyuu 的出生地是？',
      options: ['中国上海', '中国北京', '日本东京', '中国香港'],
      answer: 0,
      explain: '她出生在中国上海，本人特意强调过「纯上海人」。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: 'Liyuu 的生日是？',
      options: ['2002 年 9 月 30 日', '1997 年 1 月 9 日', '1998 年 5 月 16 日', '1995 年 3 月 3 日'],
      answer: 1,
      explain: '1997 年 1 月 9 日生。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她的身高 169cm 在 Love Live! 系列声优里是什么水平？',
      options: ['最矮', '中等', '并列第二', '最高'],
      answer: 3,
      explain: '169cm 是 LL 系列声优里的最高纪录，此前是 164.5cm 的高槻加奈子。',
    },
    {
      id: 'q5',
      level: 'easy',
      prompt: '她写进资料的特技不包括下面哪一项？',
      options: ['绘画', '饶舌', '古典芭蕾', '唱歌'],
      answer: 2,
      explain: '她的特技是绘画、饶舌与唱歌；古典芭蕾是青山渚的特长。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她 2020 年 1 月作为歌手出道的首张单曲是？',
      options: ['《Magic Words》', '《Fo(u)r YuU》', '《はつらじ》', '《YuU Koi Days》'],
      answer: 0,
      explain: '首张单曲《Magic Words》于 2020 年 1 月 22 日发售。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她的粉丝名是？',
      options: ['鲤友', '鱼民', '可可党', '上海帮'],
      answer: 0,
      explain: '粉丝名是「鲤友」（こいとも），2021 年 5 月在她的个人活动上公布。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她大学读的专业是？',
      options: ['音乐表演', '日本文学', '动画制作', '视觉传达设计'],
      answer: 3,
      explain: '大学学的是视觉传达设计（也做过饭团、零食的包装设计），2019 年毕业。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她的首张个人专辑是？',
      options: ['《Fo(u)r YuU》', '《Magic Words》', '《Ristuki》', '《Hatsuraji》'],
      answer: 0,
      explain: '首张专辑《Fo(u)r YuU》于 2022 年 2 月 9 日发售，随后在 Pacifico 横滨办了首次个人演唱会。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她早期的网名「黎狱」是怎么来的？',
      options: ['大学社团的绰号', '中二病时期自己取的', '粉丝投票选出来的', '事务所给取的艺名'],
      answer: 1,
      explain: '「黎狱」是她中二病时期取的，后来觉得羞耻才改成纯英文的 Liyuu。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '关于她的运动能力，下列说法符合她自述的是？',
      options: [
        '长跑很强，短跑不行',
        '800 米从没及格过，但仰卧起坐很拿手',
        '所有项目都不行，包括仰卧起坐',
        '拿过校运会短跑名次',
      ],
      answer: 1,
      explain: '她自述 800 米从小到大没及格过，但仰卧起坐很擅长，被弹幕调侃为「鲤鱼打挺」。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '2022 年 7 月让 Liella! 生放送取消的事件是？',
      options: ['录音室设备故障', '她本人确诊新冠', '乘坐的出租车发生交通事故', '台风导致交通中断'],
      answer: 2,
      explain: '2022 年 7 月 3 日她与伊达小百合、Payton尚未等人乘坐出租车时遭遇交通事故，7 月活动全部取消。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她的 MBTI 测试结果后来更正成了什么？',
      options: ['INFP', 'ENTJ', 'ISFJ', 'ESFP'],
      answer: 1,
      explain: '最初测出 ENTP-T，2024 年 6 月的直播里更正为 ENTJ。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '她有一句关于饮食的宣言，大意是？',
      options: ['「没有甜点的一天不算一天。」', '「我先吃蔬菜再吃肉。」', '「人没有碳水就活不下去。」', '「一天两杯咖啡是底线。」'],
      answer: 2,
      explain: '她说过「人没有碳水就活不下去」，平时蔬菜吃得少就靠蔬菜汁补。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她 2013 年第一次 cosplay 的角色是？',
      options: ['高坂穗乃果', '筒隐月子', '平泽唯', '初音未来'],
      answer: 2,
      explain: '第一次 cos 的是《轻音少女》的平泽唯（呆唯），后来她自己吐槽当时的化妆技术看不下去。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她是怎么被事务所看中的？',
      options: ['cosplay 时被星探挖掘', '参加声优养成所选拔', '在歌唱比赛中获奖', '朋友介绍进公司'],
      answer: 0,
      explain: '她 2018 年与 Horipro International 签约，本人说是在 cosplay 时被星探挖掘。',
    },
    {
      id: 'q17',
      level: 'normal',
      prompt: '她在 LL 系列里创下的纪录是？',
      options: [
        '第一位来自日本的 LL 主役',
        '第一位外国人、也是第一位中国人主役',
        '第一位在籍时 solo 出道的 LL 主役',
        '第一位兼作词作曲的 LL 主役',
      ],
      answer: 1,
      explain: '2020 年 12 月公布她出演唐可可，是 LL 系列企划第一位中国人主役，也是第一位外国人主役。',
    },
    {
      id: 'q18',
      level: 'normal',
      prompt: '2019 年 6 月 8 日她举办了什么活动？',
      options: ['个人首场演唱会', '首张单曲发售纪念签售', '首次个人 Fan Meeting', 'Fan Club 成立大会'],
      answer: 2,
      explain: '2019 年 6 月 8 日举办首次个人 Fan Meeting「Liyuu ファンミーティング VOL1」。',
    },
    {
      id: 'q19',
      level: 'normal',
      prompt: '她的首次个人演唱会办在哪里？',
      options: [
        '2021 年在 Zepp Tokyo',
        '2023 年 5 月在日本武道馆',
        '2022 年 8 月在大阪城ホール',
        '2022 年 2 月在 Pacifico 横滨',
      ],
      answer: 3,
      explain: '2022 年 2 月 11 日的《Fo(u)r YuU》演唱会办在 Pacifico 横滨国立大礼堂，并在 Bilibili 同步转播。',
    },
    {
      id: 'q20',
      level: 'normal',
      prompt: '她的个人 Fan Club 名叫？',
      options: ['鲤友会', 'YuU Koi Days', 'Yuu Days', 'Ristuki Club'],
      answer: 1,
      explain: '2020 年 10 月 12 日建立的 Fan Club 名为 YuU Koi Days，以 app 形式发放会员限定视频与周边信息。',
    },
    {
      id: 'q21',
      level: 'normal',
      prompt: '她的个人日语广播节目名叫？',
      options: ['《Liyuuのきまぐれラジオ》', '《鲤鱼の部屋》', '《Liyuuのはつらじ》', '《YuU Radio》'],
      answer: 2,
      explain: '2021 年 2 月 26 日上线个人日语广播《Liyuuのはつらじ》。',
    },
    {
      id: 'q22',
      level: 'normal',
      prompt: '她为什么常被粉丝调侃成「三文鱼」？',
      options: [
        '因为她最喜欢吃三文鱼',
        '因为她演的角色爱吃鱼',
        '因为她应援色是三文鱼色',
        '因为她汉语、英语、日语都很好，三种语言切换自如',
      ],
      answer: 3,
      explain: '她成长于中国义务教育，汉语和英语都很好，到日本工作后日语也突飞猛进，因此被调侃为「三文鱼」。',
    },
    {
      id: 'q23',
      level: 'normal',
      prompt: '她的两项「生活技能短板」是？',
      options: ['不会开车、不会骑自行车', '不会做饭、不会游泳', '不会用洗衣机、不会打字', '不会化妆、不会拍照'],
      answer: 0,
      explain: '她不会开车也不会骑自行车；做饭也不太会，常去「711 大饭店」等便利店解决。',
    },
    {
      id: 'q24',
      level: 'normal',
      prompt: '她作为 Liella! 声优第一次公开玩 SIF 时打得很糟，结果带来的「福利」是？',
      options: ['官方追加了一场补偿演唱会', '国服每位玩家获得了一张 11 连招募券', '她当场立下苦练宣言', '节目破例加更一期'],
      answer: 1,
      explain: '那次她连击不到 C，但国服玩家每人拿到一张 11 连招募券，粉丝笑称「快说谢谢鲤鱼姐」。',
    },
    {
      id: 'q25',
      level: 'hard',
      prompt: '在 SIF 九周年生放送上，她打 EX 难度打出 574/576 Combo，用的是哪首歌？',
      options: ['《Snow halation》', '《MIRAI TICKET》', '《近未来ハッピーエンド》', '《Tiny Stars》'],
      answer: 2,
      explain: '《近未来ハッピーエンド》这一场打出 574/576 Combo，被粉丝称为她的「正名之战」。',
    },
    {
      id: 'q26',
      level: 'hard',
      prompt: '她在 Liella! 通知环节念标题时被队友夸赞，但有一个词读得和英语母语者不一样，是？',
      options: ['LoveLive!', 'Superstar', 'Starlines', 'Presents'],
      answer: 3,
      explain: '她当时把跨年演唱会标题念得十分标准，引得队友阵阵夸赞，但 Presents 的读法和 native speaker 不一样。',
    },
    {
      id: 'q27',
      level: 'hard',
      prompt: '2021 年 12 月 29 日的广播里她口误把「宫城公演」说成了什么？',
      options: ['「小宫公演」', '「近江公演」', '「银座公演」', '「名古屋公演」'],
      answer: 0,
      explain: '她说成「小宫公演」，引起群体爆笑——小宫有纱是 LoveLive! 里的前辈声优。',
    },
    {
      id: 'q28',
      level: 'hard',
      prompt: '她和法元明菜第一次见面是在哪里？',
      options: ['Bilibili 的直播连线', 'LLSP 动画第 1 集录音的片场', '跨年演唱会的后台', '代代木公园的赏花会'],
      answer: 1,
      explain: '两人初次见面在动画第 1 集录音片场，她对菜宝的第一印象是「她真的会说中文啊？」。',
    },
    {
      id: 'q29',
      level: 'hard',
      prompt: '她与同唱片公司的铃木爱奈有一段缘分，是因为两人分别为哪部动画唱了 OP 和 ED？',
      options: ['《公主连结》', '《CLANNAD》', '《奇幻☆怪盗》', '《LoveLive! Superstar!!》'],
      answer: 2,
      explain: '《奇幻☆怪盗》的 OP 是 Liyuu 的艺人出道曲，ED 由铃木爱奈演唱，两人还一起参加了动画特别访谈。',
    },
    {
      id: 'q30',
      level: 'hard',
      prompt: '她第一次去日本是什么时候？',
      options: ['初中修学旅行', '高中交换留学', '大学毕业后', '高考结束的暑假'],
      answer: 3,
      explain: '第一次去日本是高考结束的暑假，当时她还不会说日语。',
    },
    {
      id: 'q31',
      level: 'hard',
      prompt: '她公开说过的一个梦想是？',
      options: [
        '在中国国内开一次全是汉语歌曲的演唱会',
        '在日本武道馆办个人演唱会',
        '出一本自己的画集',
        '和初音未来合作一首歌',
      ],
      answer: 0,
      explain: '她的梦想是在中国国内开一次全是汉语歌曲的演唱会。',
    },
    {
      id: 'q32',
      level: 'hard',
      prompt: '她自称在 Liella! 里最擅长的一件事是？',
      options: ['做饭', '模仿队友与角色的说话方式', '记舞蹈动作', '拍照'],
      answer: 1,
      explain: '她是队里的「模仿大师」，常模仿动画里的理事长与薇恩喊「涩谷香音」，队友听了就笑。',
    },
  ],
} satisfies SeiyuuQuizBank;
