import type { SeiyuuQuizBank } from '../types';

/**
 * 大熊和奏（若菜四季）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/大熊和奏
 */
export default {
  id: 'okuma-wakana',
  groups: ['liella'],
  intro: 'Liella! 二期生的大熊和奏。会游泳、和太鼓、舞蹈，见面就说「想和大家扭打在一起」的怪人。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '大熊和奏在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['米女芽衣', '若菜四季', '樱小路希奈子', '鬼冢夏美'],
      answer: 1,
      explain: '她饰演二期生若菜四季，2022 年 5 月 12 日作为 Liella! 2 期生公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '大熊和奏的生日是？',
      options: ['2001 年 4 月 13 日', '2001 年 7 月 18 日', '2002 年 11 月 1 日', '1999 年 3 月 8 日'],
      answer: 0,
      explain: '2001 年 4 月 13 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她写进资料的特长不包括下面哪一项？',
      options: ['游泳', '和太鼓', '舞蹈', '步枪射击'],
      answer: 3,
      explain: '特长是游泳、和太鼓与舞蹈；步枪射击是薮岛朱音的特长。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她所属的事务所是？',
      options: ['Apollo Bay', 'Holy Peak', '贤Production', 'I\u0027m Enterprise'],
      answer: 2,
      explain: '她属于贤Production。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她从幼儿园时就开始学的两项是？',
      options: ['爵士舞与游泳', '钢琴与小提琴', '书法与茶道', '空手道与剑道'],
      answer: 0,
      explain: '幼儿园起开始跳爵士舞和游泳，这也成了她后来特长的基础。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她家里养了什么宠物？',
      options: ['两只狗', '一只猫', '一只鹦鹉', '热带鱼'],
      answer: 1,
      explain: '她家里养了一只猫。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她喜欢的食物是？',
      options: ['蜜瓜与纳豆', '白菜卷与饭团', '巧克力与鲑鱼', '红薯与拉面'],
      answer: 2,
      explain: '她喜欢巧克力与鲑鱼，喜欢的歌手是 Serph。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她 2023 年开设的个人 niconico 节目名叫？',
      options: ['《熊的散步道》', '《和奏的音乐室》', '《自由地活着》', '《大熊和奏的 Bears Be Ambitious》'],
      answer: 3,
      explain: '2023 年 4 月 3 日宣布开设《大熊和奏のBears Be Ambitious》，4 月 12 日首次直播。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '2026 年她作为组合成员获得了第 20 届声优奖的哪个奖？',
      options: ['歌唱赏', '新人赏', '主演声优赏', '最佳主持赏'],
      answer: 0,
      explain: '她作为 AiScReam 成员获得第 20 届声优奖歌唱赏。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她自认擅长做的一道料理是？',
      options: ['白菜卷', '炒蛋', '韩式胡萝卜煎饼', '明石烧'],
      answer: 2,
      explain: '她擅长做韩式胡萝卜煎饼。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她的人生格言是？',
      options: ['「先做完再不情愿」', '「每天都要吃早饭」', '「一步一步慢慢来」', '「自由地活着，不论一切都拼劲全力」'],
      answer: 3,
      explain: '这句格言来自她初中时的恩师。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她回家后做的第一件事通常是？',
      options: ['先去厨房找吃的', '打开电视看番', '给猫喂食', '直接睡一觉'],
      answer: 0,
      explain: '她回家后第一件事就是去厨房找吃的。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: 'Liella! 成员初次见面时，她说出过一句让铃原希实头疼了很久的话，是？',
      options: ['「希望能和大家扭打在一起」', '「大家一起去泡温泉吧」', '「我想住到队友家里」', '「以后每天都要抱一下」'],
      answer: 0,
      explain: '她想和大家成为「吵架互殴、拼尽一切，然后躺在草地上」的关系，铃原希实为此焦急了很久。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '2023 年 4 月 9 日的活动上，她留下了哪个出圈名场面？',
      options: ['「神之一跪」', '「神之一指」', '「神之一笑」', '「神之一叹」'],
      answer: 1,
      explain: '在「Liella! LieRadi! 公开收录 2023」上大笑，留下「神之一指」的名场面。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她 2024 年 8 月起以哪个名义开展艺人活动？',
      options: ['Kumakuma', 'Wakana', 'Spileben', 'AiScReam'],
      answer: 2,
      explain: '2024 年 8 月 30 日宣布以「Spileben」名义在 Bandai Namco Music Live 旗下 StarRise 开展艺人活动，2025 年 4 月退所后仍继续该名义的音乐活动。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她在加入 Liella! 之前的发型是？',
      options: ['短发', '双马尾', '蘑菇头', '长发'],
      answer: 3,
      explain: '她原本是长发，薮岛朱音还以为她是个成熟稳重的大姐姐。',
    },
  ],
} satisfies SeiyuuQuizBank;
