import type { SeiyuuQuizBank } from '../types';

/**
 * Payton尚未（平安名堇）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/ペイトン尚未
 */
export default {
  id: 'payton-naomi',
  groups: ['liella'],
  intro: 'Liella! 的平安名堇。啦啦队舞全国第二、初音未来狂热粉，自称「世界上第一个爱上堇的人」。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: 'Payton尚未在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['岚千砂都', '平安名堇', '叶月恋', '涩谷香音'],
      answer: 1,
      explain: '她饰演平安名堇，并且多次自认是「堇激推」。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: 'Payton尚未的生日是？',
      options: ['2003 年 7 月 1 日', '1999 年 3 月 8 日', '2002 年 9 月 30 日', '1997 年 1 月 9 日'],
      answer: 0,
      explain: '2003 年 7 月 1 日生，埼玉县川越市出身。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她的出生地是？',
      options: ['京都府京都市', '东京都', '埼玉县川越市', '神奈川县横滨市'],
      answer: 2,
      explain: '她出生在埼玉县川越市；母亲是京都人，所以她也爱吃京都拉面。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料、拿到全国第 2 名的特长是？',
      options: ['古典芭蕾', '茶道', '书法', '啦啦队舞'],
      answer: 3,
      explain: '特长是啦啦队舞，曾拿到全国第 2 名，另外还会唱歌。',
    },
    {
      id: 'q5',
      level: 'easy',
      prompt: '她所属的事务所是？',
      options: ['Sony Music Artists', 'Holy Peak', 'Apollo Bay', '响 HiBiKi'],
      answer: 0,
      explain: '她属于 Sony Music Artists，Fan Club 名叫「ペヰトン浪漫」。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她作为声优出道的作品与角色是？',
      options: ['《BATON=RELAY》的高桥京子', '《Love Live! Superstar!!》的平安名堇', '《美妙天堂》的北条索菲', '《偶像活动》的大空明'],
      answer: 0,
      explain: '2019 年 8 月 1 日，她为手机游戏《BATON=RELAY》的高桥京子配音，正式声优出道。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她的家庭背景是？',
      options: ['父母都是日本人', '父亲是日本人、母亲是美国人', '父亲是美国人、母亲是京都人', '父母都在国外长大'],
      answer: 2,
      explain: '父亲是美国人、母亲是日本京都人，家里还有一个弟弟。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她的英语检定成绩是？',
      options: ['准 1 级', '2 级', '3 级', '准 2 级'],
      answer: 3,
      explain: '2020 年 3 月拿到日本英语检定准 2 级合格。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她家里养的两只宠物是？',
      options: ['黑猫与迷你杜宾犬', '橘猫与柴犬', '仓鼠与鹦鹉', '两只博美犬'],
      answer: 0,
      explain: '一只黑猫名叫 Love酱，一只迷你杜宾犬名叫 Let君，因为脑袋像炸鸡被粉丝叫「炸鸡」。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她非常不喜欢、几乎不碰的调味品是？',
      options: ['芥末', '蛋黄酱', '番茄酱', '味噌'],
      answer: 1,
      explain: '她非常不喜欢蛋黄酱；奶油倒是爱到买 1L 装每天涂面包。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她最喜欢的虚拟歌手是？',
      options: ['镜音铃', '巡音流歌', '初音未来', 'MEIKO'],
      answer: 2,
      explain: '她是初音未来的狂热粉丝，家里堆满周边和 DVD，参加 2019 年 MAGICAL MIRAI 时自称哭了 4 次。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她小时候最想从事的职业是？',
      options: ['医生', '老师', '海豚训练师', '魔法少女'],
      answer: 3,
      explain: '她小时候想当魔法少女，其次是偶像，再次是海豚。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她 2023 年个人歌手出道的单曲是？',
      options: ['《魔法》', '《泡沫》', '《浪漫》', '《魔法*》'],
      answer: 0,
      explain: '2023 年 3 月以《魔法》歌手出道，3 月 21 日办了 1st live；后来还有 2nd live《泡沫》与 +1st live《魔法*》。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '在《Liella! 突击外景》里她算出的「270×2-35」是多少？',
      options: ['505', '515', '495', '535'],
      answer: 1,
      explain: '正解是 505，她算成了 515，是当时全员里唯一算错的人。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她未成年时不能参加 22 点后的深夜直播，当时的解决办法是？',
      options: ['由队友代读留言', '只录播不发直播', '用立牌代替本人出镜', '把节目提前到 21 点'],
      answer: 2,
      explain: '当时用立牌代替她本人，于是有了「纸片人 Payton尚未」这个梗。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她的个人连载是在哪本杂志的 2022 年 vol.47 开始刊载的？',
      options: ['《声優グランプリ》', '《B.L.T.》', '《MyGirl》', '《声優パラダイスR》'],
      answer: 3,
      explain: '2022 年 3 月 21 日发售的《声優パラダイスR》vol.47 起开始她本人的连载。',
    },
  ],
} satisfies SeiyuuQuizBank;
