import type { SeiyuuQuizBank } from '../types';

/**
 * 铃原希实（樱小路希奈子）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/鈴原希実
 */
export default {
  id: 'suzuhara-nozomi',
  groups: ['liella'],
  intro: 'Liella! 二期生的铃原希实。练了 8 年书法、爱画女孩子，被队友说像小动物一样让人想保护。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '铃原希实在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['米女芽衣', '樱小路希奈子', '若菜四季', '鬼冢夏美'],
      answer: 1,
      explain: '她饰演二期生樱小路希奈子，2022 年 5 月 12 日作为 Liella! 2 期生公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '铃原希实的生日是？',
      options: ['2002 年 11 月 1 日', '2001 年 7 月 18 日', '2003 年 7 月 1 日', '2001 年 4 月 13 日'],
      answer: 0,
      explain: '2002 年 11 月 1 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她写进资料的特长不包括下面哪一项？',
      options: ['书法', '画女孩子的插图', '双利手', '空手道'],
      answer: 3,
      explain: '特长是书法、画女孩子的插图与双利手（两手都能用）。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她所属的事务所是？',
      options: ['Holy Peak', 'I\u0027m Enterprise', '贤Production', 'Apollo Bay'],
      answer: 3,
      explain: '2022 年 5 月 12 日成为 Apollo Bay 所属，与伊达小百合、青山渚同社。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她练了多少年的书法？',
      options: ['8 年', '3 年', '5 年', '12 年'],
      answer: 0,
      explain: '她学过 8 年书法，这也是她写进资料的特长之一。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她的昵称「Non酱」是怎么来的？',
      options: ['粉丝投票选的', '父母喜欢的漫画里有个 Non 酱，想用这个名字称呼孩子', '姐姐小时候这样叫她', '她自己觉得好听就用了'],
      answer: 1,
      explain: '父母喜欢的漫画里有叫 Non 酱的角色，本想用 Non 酱称呼孩子，最后取了「希实」这个名字，昵称也就成了 Non 酱。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '以下哪一组是她的爱好？',
      options: ['钓鱼、露营、摄影', '篮球、唱歌', '漫画、逛面包店、卡牌游戏', '书法、茶道、盆栽'],
      answer: 2,
      explain: '爱好是漫画、逛面包店与卡牌游戏；周末常在画画或看漫画。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '她有一个从小就有的「苦手」项目，是？',
      options: ['过山车', '人多的地方', '打电话', '接触动物'],
      answer: 3,
      explain: '小时候被跟自己差不多高的狗追着跑还被舔了，从此不擅长接触动物，回家路上遇到狗都要绕路。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她喜欢的面包是？',
      options: ['可颂与蒜香法式面包', '红豆面包与菠萝包', '咖喱面包与热狗卷', '全麦吐司与贝果'],
      answer: 0,
      explain: '她喜欢可颂和蒜香法式面包，还常去逛面包店。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她成为「双马尾控」的契机是？',
      options: [
        '自己小时候一直扎双马尾',
        '姐姐带她看早安少女组的演出，觉得道重沙由美的双马尾很可爱',
        '动画角色的发型让她心动',
        '被造型师建议尝试',
      ],
      answer: 1,
      explain: '姐姐喜欢早安少女组，带她看演出时她觉得道重沙由美的双马尾很可爱，此后就成了双马尾控（尤其低双马尾）。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她自认加入 Liella! 前是「天天在家不和别人玩的阴角」，后来受谁的影响变得开朗？',
      options: ['姐姐的偶像朋友', '学校的老师', '几位 VTuber', '同社的前辈声优'],
      answer: 2,
      explain: '她喜欢看 VTuber，受莉泽·赫露艾斯塔、安洁·卡特莉娜、戌亥床三人影响变得开朗，并去挑战了 LoveLive! Superstar!! 的公开招募。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她在卡拉 OK 一定会唱的歌是？',
      options: ['《Snow halation》', '《START:DASH!!》', '《夏色えがおで1,2,Jump!》', '《恋爱裁判》'],
      answer: 3,
      explain: '她自述在卡拉 OK 一定会唱《恋爱裁判》。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '2023 年她担任了广播「ラジオどっとあい」第几代主持人？',
      options: ['第 92 代', '第 87 代', '第 100 代', '第 84 代'],
      answer: 0,
      explain: '2023 年 4 月起她是第 92 代主持人，为期 3 个月。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '她 2023 年开设的个人 niconico 节目名叫？',
      options: ['《Non酱的自由研究》', '《铃原希实 我的人生，Nonfiction。》', '《希实的面包店巡礼》', '《Nonfiction 周刊》'],
      answer: 1,
      explain: '2023 年 4 月 5 日宣布开设《铃原希実 わたしの人生、ノンフィクション。》。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她画画时会进入高度集中状态，最长曾经连续画了多久？',
      options: ['2 小时', '3 小时', '5 小时', '8 小时'],
      answer: 2,
      explain: '一旦开始画画精神就高度集中，曾连续画过 5 小时。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她自认擅长做的一道料理是？',
      options: ['蛋包饭', '味噌汤', '咖喱', '炒蛋'],
      answer: 3,
      explain: '她擅长炒蛋；另外她吃饭很慢，学校配餐时别人吃完了她还在吃。',
    },
  ],
} satisfies SeiyuuQuizBank;
