import type { SeiyuuQuizBank } from '../types';

/**
 * 内田秀（米娅·泰勒）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/内田秀
 */
export default {
  id: 'uchida-shuu',
  groups: ['nijigasaki'],
  intro: '米娅·泰勒的饰演者。悉尼长大、TOEIC 满分、养着萨摩耶的「秀老师」。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '内田秀在虹咲同好会里饰演的角色是？',
      options: ['艾玛·维尔德', '米娅·泰勒', '钟岚珠', '三船栞子'],
      answer: 1,
      explain: '她饰演来自美国的转校生米娅·泰勒。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '内田秀的生日是？',
      options: ['2 月 27 日', '12 月 22 日', '5 月 24 日', '8 月 5 日'],
      answer: 2,
      explain: '1996 年 5 月 24 日生。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '内田秀成长的地方是？',
      options: ['日本广岛', '日本大阪', '美国洛杉矶', '澳大利亚悉尼'],
      answer: 3,
      explain: '她在日本广岛出生，约两岁半起在澳大利亚悉尼生活了 18 年。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她第一次参与的声优工作是？',
      options: [
        '《舰队Collection》的厌战',
        '《爱丽丝与藏六》',
        '《LoveLive!虹咲学园学园偶像同好会》',
        '《死神》',
      ],
      answer: 0,
      explain: '2016 年 8 月为《舰队Collection》的厌战配音，是她第一份声优工作；首个主役是《爱丽丝与藏六》。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '她在澳大利亚读大学时学的专业是？',
      options: [
        '幼儿教育',
        '金融，并选修法律',
        '机械工程',
        '声乐',
      ],
      answer: 1,
      explain: '她在悉尼大学学金融、选修法律，后来为了追声优梦瞒着父母辍学去了日本。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '关于她的英语水平，下面哪个说法是真的？',
      options: [
        '她只会说日语和一点点英语',
        '她考过英语教师资格证但没考过 TOEIC',
        '2021 年参加 TOEIC 考试拿到满分',
        '她英语不太好，所以来日本发展',
      ],
      answer: 2,
      explain: '她英语接近母语水平（在当地生活 18 年），2021 年在 TOEIC 考试中拿到满分。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '除了日语和英语，她还学过下面哪些语言？',
      options: [
        '只学过法语和德语',
        '只学过韩语',
        '只学过西班牙语',
        '汉语、韩语、意大利语，以及一点澳大利亚土著语言',
      ],
      answer: 3,
      explain: '她学过汉语（小学时期＋法元明菜教学）、韩语（朋友指导＋追韩剧）、意大利语，还学过一点澳大利亚土著语言，但后两者已经忘得差不多。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '关于她养狗的经历，下面哪个说法是对的？',
      options: [
        '先养了博美 Papiko，后来养了萨摩耶 Mooni',
        '她只养猫，不养狗',
        '她养的是柴犬',
        '她一直想养狗但因过敏不能养',
      ],
      answer: 0,
      explain: '她 2023 年公开养了博美 Papiko，2024 年又养了萨摩耶 Mooni（后来 Mooni 在 2025 年离世）。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '2021 年她开设的个人 YouTube 频道「ShuTube」主要做什么内容？',
      options: [
        '只教英语语法',
        '英日双语分享日本文化与澳大利亚的文化差异',
        '只做游戏实况',
        '只唱歌投稿',
      ],
      answer: 1,
      explain: 'ShuTube 用英日双语创作，主题是日本文化与澳大利亚文化差异，双语字幕由她本人编辑。',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '她在 2023 年考取的执照是？',
      options: ['空手道初段', '簿记三级', '马术五级', '小型船舶驾驶'],
      answer: 2,
      explain: '她 2023 年 2 月末通过马术五级考试并取得执照；另外她在 2024 年 1 月拿到驾照。',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '她有过两次「电子设备遭殃」的记录，分别是？',
      options: [
        '手机掉进拉面汤里；耳机被狗咬坏',
        '把平板当成砧板；把键盘泼了咖啡',
        '相机掉进海里；充电宝被雪埋了',
        'AirPods 忘在洗衣机里洗了；手机过热被她放进冰水降温',
      ],
      answer: 3,
      explain: '她把 AirPods 忘在洗衣机里（粉丝叫「AirPods Shower」），2023 年 7 月又因为手机过热干脆把手机泡进冰水降温。',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '她的座右铭是？',
      options: [
        'Open the door, it may lead you to someplace never expected.',
        'Seize the day.',
        'No pain, no gain.',
        'Simple is best.',
      ],
      answer: 0,
      explain: '她的座右铭是「Open the door, it may lead you to someplace never expected.」',
    },
    {
      id: 'q13',
      level: 'normal',
      prompt: '她最喜欢的咖啡种类是？',
      options: ['卡布奇诺', '美式', '拿铁', '摩卡'],
      answer: 0,
      explain: '她爱咖啡，最喜欢卡布奇诺；来日本后常点大杯拿铁加一份浓缩。',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '因为太爱吃汉堡，她学会了一句很奇怪的汉语，是？',
      options: ['「你吃饭了吗」', '「你想要我的汉堡包吗」', '「我很饿」', '「汉堡真好吃」'],
      answer: 1,
      explain: '她非常喜欢汉堡，甚至把「你想要我的汉堡包吗」这句汉语学会了。',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '她的 MBTI 是？',
      options: ['INFP', 'ISTJ', 'ENFJ', 'ENTP'],
      answer: 2,
      explain: '她测出的是 ENFJ，还说 ENFJ 与 INFP 相性很好；大西亚玖璃也提到过自己的 MBTI。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她的家人现在住在哪里？',
      options: ['东京', '大阪', '广岛', '双亲都居住在海外'],
      answer: 3,
      explain: '她双亲都住在海外，2023 年 1 月家人来日本旅行时，顺便看了她参演的 R3BIRTH Live。',
    },
    {
      id: 'q17',
      level: 'hard',
      prompt: '她公开说过的梦想是？',
      options: ['成为在海外奋斗的声优', '开一家咖啡店', '当英语老师', '成为歌手兼作曲家'],
      answer: 0,
      explain: '她的梦想是成为在海外奋斗的声优。',
    },
    {
      id: 'q18',
      level: 'hard',
      prompt: '2025 年 5 月她在推特宣布自己抢到了什么，还胜过众多业界同仁？',
      options: ['演唱会门票', 'Switch 2 的购买资格', '限量吉他', '马术比赛名额'],
      answer: 1,
      explain: '她开心宣布获得了 Switch 2 的购买资格，还「击败」了一堆业界同仁。',
    },
  ],
} satisfies SeiyuuQuizBank;
