import type { SeiyuuQuizBank } from '../types';

/**
 * 彩蛋人物：玩机器Machine（斗鱼 6657）。
 *
 * 资料：萌娘百科 https://zh.moegirl.org.cn/玩机器Machine
 * 他不是女声优，所以**不在** `@seiyuu/shared` 名册里，身份声明见 `../index.ts` 的
 * `EASTER_EGG_IDENTITIES`。加进来的理由见最后一题——一位和女声优有莫大关系的主播。
 */
export default {
  id: 'wjq-machine',
  intro:
    '斗鱼 6657，一位能把 CS:GO 解说成单口相声的主播。严格来说不是女声优，但他和《MyGO!!!!!》里某位角色的关系，让他在这个站里必须拥有姓名。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '玩机器Machine 主要在哪家平台直播？',
      options: ['斗鱼', '虎牙', 'B 站', '抖音'],
      answer: 0,
      explain: '他是斗鱼直播平台的 CS:GO 主播兼赛事解说，长期在斗鱼开播。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '他的直播间房间号是多少？（这个数字后来也直接代指他本人）',
      options: ['6675', '6657', '6765', '6557'],
      answer: 1,
      explain: '直播间房间号是 6657，「6657」已经成了他和水友之间的共同暗号。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '他直播与解说生涯里最有名的游戏是？',
      options: ['英雄联盟', 'DOTA2', 'CS:GO', '绝地求生'],
      answer: 2,
      explain: '以 CS:GO 主播与赛事解说成名（DOTA2 也懂，但主业是 CS:GO）。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '2025 年 5 月他自述最喜欢的《BanG Dream!》角色是？',
      options: ['丰川祥子', '高松灯', '长崎素世', '千早爱音'],
      answer: 2,
      explain:
        '他明确说自己喜欢《MyGO!!!!!》的长崎素世。这就是他和本站的缘分：长崎素世的声优是站内名册里的小日向美香。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '他解说时爱用（也常常误用）成语，水友给他起了什么称号？',
      options: ['成语大师', '诗词大家', '歇后语之王', '字典本人'],
      answer: 0,
      explain: '「成语大师」。误用如「三人成虎」「聪明一世」，反而催生了水友的造梗热情。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '水友爱用「6657 + 四字词」刷弹幕，其中调侃他开播频率的是哪一句？',
      options: ['播七休一', '播一休七', '休一播七', '一播七休'],
      answer: 1,
      explain: '「6657 播一休七」——播一天休七天，配合他的「鸽子」人设食用。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '他常在游戏内的监管系统里「执行正义」，因此得了哪个外号？',
      options: ['玩大人', '玩校长', '玩法官', '玩大爷'],
      answer: 0,
      explain: '监管系统让玩家扮演「法官」，常做监管的他就被叫成「玩大人」了。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '玩机器Machine 的本名是？',
      options: ['刘一博', '陈亦博', '何红雨', '刘亦博'],
      answer: 3,
      explain: '本名刘亦博。（何红雨是另一个位置上的名字，别选错。）',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '他 2019 年的《引退宣言》以哪两句诗开篇？（后来成了「鸽了」的代称）',
      options: [
        '长风破浪会有时，直挂云帆济沧海',
        '欲渡黄河冰塞川，将登太行雪满山',
        '天生我材必有用，千金散尽还复来',
        '山重水复疑无路，柳暗花明又一村',
      ],
      answer: 1,
      explain:
        '「欲渡黄河冰塞川，将登太行雪满山」。此后水友还用「#查询黄河凌汛程度」来调侃他不开播。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q10',
      level: 'hard',
      prompt: '因为弹幕环境太差，他曾把粉丝牌发言门槛提高到多少级？',
      options: ['11 级', '31 级', '21 级', '不限等级'],
      answer: 2,
      explain: '提高到 21 级粉丝牌才能发言——不过对满屏的 6657 烂梗来说并没什么用。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q11',
      level: 'hard',
      prompt: '他打枪时会下意识张嘴，自嘲是《植物大战僵尸》里的哪个植物？',
      options: ['豌豆射手', '寒冰射手', '坚果墙', '樱桃炸弹'],
      answer: 0,
      explain: '「豌豆射手」。他还吐槽过「别一直看我的嘴啊，看我的准星」。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q12',
      level: 'hard',
      prompt: '他自称的「真实身份」是？',
      options: ['石家庄一哥', '解说之神', '鸽王', '二次元教父'],
      answer: 3,
      explain:
        '「二次元教父」。他直播里动漫梗密度极高，还曾用 Facerig 把摄像头换成动漫美少女（水友称之为「机机子」）。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q13',
      level: 'easy',
      prompt: '玩机器Machine 的生日是？',
      options: ['1996 年 1 月 11 日', '1994 年 3 月 5 日', '1998 年 7 月 10 日', '2000 年 2 月 18 日'],
      answer: 0,
      explain: '1996 年 1 月 11 日生，活跃年代从 2016 年算起。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q14',
      level: 'normal',
      prompt: '他直播间用的头像是哪部作品的角色？',
      options: ['《命运石之门》的牧濑红莉栖', '《Fate》系列的伊莉雅', '《Re:从零开始》的蕾姆', '《刀剑神域》的亚丝娜'],
      answer: 1,
      explain: '直播间头像是 Fate 系列的伊莉雅，游戏内头像则是《命运石之门》的牧濑红莉栖。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q15',
      level: 'normal',
      prompt: '「北美玩机器」这个说法是怎么来的？',
      options: [
        '他自己在直播里自封的',
        '水友觉得他和 Shroud 长得像',
        'CS:GO 官方微博称 Shroud 为「北美玩机器」',
        '他在北美赛区打过职业',
      ],
      answer: 2,
      explain:
        '他在加拿大留学时视 Shroud 为偶像，把 ID 设成「C9 的 shroud 本人」；后来 CS:GO 官方微博称 Shroud 为「北美玩机器」，这个称呼就坐实了。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q16',
      level: 'normal',
      prompt: '2018 年完美世界庆典给了他哪两项荣誉？',
      options: [
        '最佳新人解说与最佳节目',
        '年度最佳主播与最佳内容创作者',
        '最佳电竞经理与最佳教练',
        '年度最具人气解说与玩家最喜爱的 CS:GO 主播',
      ],
      answer: 3,
      explain: '他在 2018 年拿到「年度最具人气解说」和「玩家最喜爱的 CS:GO 主播」两项。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q17',
      level: 'normal',
      prompt: '除了直播解说，他还拿过一个冠军，是在哪场比赛？',
      options: ['2017 年完美城市精英赛（Ephorse 一匹马战队）', '2019 年完美世界 DOTA2 邀请赛', '2020 年斗鱼黄金大奖赛', '2018 年 ESL 中国区预选'],
      answer: 0,
      explain: '2017 年完美城市精英赛上，他所在的 Ephorse 一匹马战队夺得冠军。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q18',
      level: 'hard',
      prompt: '2019 年 2 月发表引退宣言后，他大约什么时候正式复播？',
      options: ['一个月后', '2019 年 6 月左右', '2020 年 1 月', '再也没有复播'],
      answer: 1,
      explain: '宣言收到水友、同行和多家电竞俱乐部的鼓励，他最终在 2019 年 6 月左右正式复播。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q19',
      level: 'hard',
      prompt: '他在 2021 年 4 月 30 日做了什么？',
      options: ['宣布退役', '开了个人公司', '和何红雨结婚', '搬去加拿大定居'],
      answer: 2,
      explain: '2021 年 4 月 30 日，他与何红雨结婚。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q20',
      level: 'hard',
      prompt: '直播间疯传的「咬人猫」事件是怎么回事？',
      options: [
        '他邀请咬人猫来直播间连麦',
        '他和咬人猫合作出了单曲',
        '他给咬人猫刷了礼物榜第一',
        '他的 B 站账号收藏夹被发现收藏了咬人猫的视频，本人后来说自己并不看',
      ],
      answer: 3,
      explain: '水友发现他 B 站收藏夹里有舞蹈区 up 主咬人猫的视频，事情越闹越大，他后来在直播里回应自己并不看，希望大家别过度玩梗。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q21',
      level: 'hard',
      prompt: '水友口中的「机机子」指的是？',
      options: ['他用 Facerig 把摄像头形象换成动漫美少女后的虚拟形象', '他养的猫', '他的女装形象', '他的第二个直播间'],
      answer: 0,
      explain: '他用面部捕捉软件 Facerig 把摄像头换成动漫美少女，于是水友开玩笑说这是 Vtuber「机机子」。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q22',
      level: 'normal',
      prompt: '「穷玩车，富玩表，傻逼玩机器」这句话其实是？',
      options: ['黑粉的攻击口号', '粉丝对他的爱称', '其他主播的挑衅', '他的直播间标语'],
      answer: 1,
      explain: '因为他爱搞行为艺术，水友把这句当成了爱称，而不是骂人。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q23',
      level: 'hard',
      prompt: '2018 年拿到「年度最具人气解说」之后，他为什么消失了 4 个月？',
      options: ['去加拿大留学', '结婚度蜜月', '因为身体原因鸽了', '被平台封号'],
      answer: 2,
      explain: '他因为身体原因鸽了 4 个月，这也是「鸽子」人设的来源之一。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
    {
      id: 'q24',
      level: 'normal',
      prompt: '下面哪一句是他的「公式解说」口头禅？',
      options: ['「这波不亏，血赚」', '「我们下期再见」', '「让我们恭喜这位选手」', '「让人不禁感叹这就是……啊」'],
      answer: 3,
      explain: '他的公式解说还有「让人不禁想问真的……吗」「……真的可以……吗？答案当然是可以」。',
      source: 'https://zh.moegirl.org.cn/玩机器Machine',
    },
  ],
} satisfies SeiyuuQuizBank;
