import type { SeiyuuQuizBank } from '../types';

/**
 * 薮岛朱音（米女芽衣）题库。
 * 资料：萌娘百科 https://zh.moegirl.org.cn/薮島朱音
 */
export default {
  id: 'yabushima-akane',
  groups: ['liella'],
  intro: 'Liella! 二期生的薮岛朱音。会步枪射击、爱逛面包店，甄选时的红耳环红美甲骗过了所有人。',
  questions: [
    {
      id: 'q1',
      level: 'easy',
      prompt: '薮岛朱音在 Love Live! Superstar!! 里饰演的角色是？',
      options: ['樱小路希奈子', '米女芽衣', '鬼冢夏美', '若菜四季'],
      answer: 1,
      explain: '她饰演二期生米女芽衣（米女メイ），2022 年 5 月 12 日作为 Liella! 2 期生公布。',
    },
    {
      id: 'q2',
      level: 'easy',
      prompt: '薮岛朱音的生日是？',
      options: ['2001 年 7 月 18 日', '2002 年 11 月 1 日', '2001 年 4 月 13 日', '2003 年 7 月 1 日'],
      answer: 0,
      explain: '2001 年 7 月 18 日生，神奈川县出身。',
    },
    {
      id: 'q3',
      level: 'easy',
      prompt: '她的出身地是？',
      options: ['埼玉县', '千叶县', '神奈川县', '宫崎县'],
      answer: 2,
      explain: '她出身于神奈川县。',
    },
    {
      id: 'q4',
      level: 'easy',
      prompt: '她写进资料的特长是？',
      options: ['书法', '古典芭蕾', '啦啦队舞', '步枪射击'],
      answer: 3,
      explain: '特长是步枪射击，高中加入的步枪射击部练的是非实弹的激光镭射步枪。',
    },
    {
      id: 'q5',
      level: 'normal',
      prompt: '以下哪一组是她的兴趣？',
      options: ['篮球、唱歌', '漫画、逛面包店', '游泳、和太鼓', '书法、画插图'],
      answer: 0,
      explain: '兴趣是篮球与唱歌，篮球来自初中时的篮球部。',
    },
    {
      id: 'q6',
      level: 'normal',
      prompt: '她有一种连闻味道都不行的食物，是？',
      options: ['纳豆', '蜜瓜', '牛油果', '南瓜'],
      answer: 1,
      explain: '她不吃蜜瓜，连味道都不能闻；纳豆、牛油果、南瓜反倒是她喜欢的。',
    },
    {
      id: 'q7',
      level: 'normal',
      prompt: '她最喜欢的声优是？',
      options: ['水树奈奈', '林原惠', '坂本真绫', '泽城美雪'],
      answer: 2,
      explain: '她最喜欢的声优是坂本真绫，也常去 LiSA 的 live。',
    },
    {
      id: 'q8',
      level: 'normal',
      prompt: '因为喜欢的声优，她在《Fate》系列里最喜欢的角色是？',
      options: ['Saber', '远坂凛', '间桐樱', '贞德'],
      answer: 3,
      explain: '她喜欢《Fate/stay night》系列，因为坂本真绫而最喜欢贞德。',
    },
    {
      id: 'q9',
      level: 'normal',
      prompt: '她初中时属于哪个社团？',
      options: ['篮球部', '轻音部', '步枪射击部', '茶道部'],
      answer: 0,
      explain: '初中是篮球部；步枪射击部是高中时因为时间宽裕才顺势加入的。',
    },
    {
      id: 'q10',
      level: 'normal',
      prompt: '她自认擅长做的一道料理是？',
      options: ['白菜卷', '汉堡肉', '蛋包饭', '韩式胡萝卜煎饼'],
      answer: 0,
      explain: '她擅长做白菜卷，还常和妈妈一起上料理课。',
    },
    {
      id: 'q11',
      level: 'normal',
      prompt: '她在成为声优之前的学习经历是？',
      options: [
        '大学读的是放送学科',
        '高中读的是调理科',
        '初三到高三就读日本播音演技研究所',
        '一直自学没有进过养成所',
      ],
      answer: 2,
      explain: '她初三至高三期间就读日本播音演技研究所，2020 年 4 月 1 日成为 I\u0027m Enterprise 所属。',
    },
    {
      id: 'q12',
      level: 'normal',
      prompt: '她所属的事务所是？',
      options: ['Apollo Bay', 'Sony Music Artists', '贤Production', 'I\u0027m Enterprise'],
      answer: 3,
      explain: '她 2020 年 4 月起是 I\u0027m Enterprise 所属。',
    },
    {
      id: 'q13',
      level: 'hard',
      prompt: '她把自己比作哪种动物，用来形容自己的行动速度？',
      options: ['树獭', '乌龟', '熊猫', '考拉'],
      answer: 0,
      explain: '她常说自己行动是「树獭级的慢」。',
    },
    {
      id: 'q14',
      level: 'hard',
      prompt: '参加 Liella! 二期生甄选时，她给其他三人的第一印象是？',
      options: ['安静内向的文学少女', '「不良的大姐头」「辣妹」', '元气的运动系', '稳重的成熟大姐姐'],
      answer: 1,
      explain: '甄选时她的耳环和美甲都是浮夸的大红色，队友的初印象是「不良的大姐头」「辣妹」，铃原希实还觉得这人有点可怕。',
    },
    {
      id: 'q15',
      level: 'hard',
      prompt: '她喜欢的颜色是？',
      options: ['蓝和绿', '粉和白', '红和黑', '黄和橙'],
      answer: 2,
      explain: '她喜欢红色和黑色，不留意的话买衣服总会挑到黑色系。',
    },
    {
      id: 'q16',
      level: 'hard',
      prompt: '她有一个收集爱好，是？',
      options: ['马克杯', '明信片', '香薰', '化妆品'],
      answer: 3,
      explain: '她喜欢收集化妆品。',
    },
  ],
} satisfies SeiyuuQuizBank;
