import type { SongQuizSong } from '../types';

/**
 * 偶像大师 · million 的猜歌曲库（抓取自 iTunes JP 区，含 30 秒试听）。
 *
 * 生成方式：`node --experimental-strip-types tmp/fetch-song-catalog-v2.mjs` → `node tmp/song-catalog-to-ts-v2.mjs`，不要手改。
 * - 含小队曲与声优以角色身份演唱的个人曲。
 * - `id` 是 iTunes trackId；试听地址由服务端 `/api/song-quiz/previews` 按 id 实时换取。
 * - 同一首歌的多个版本（BEST 盘、个人盘、TV size 等）已合并，只保留最早发行的版本。
 * - 按发行日期升序排列。
 */
export default [
  { id: 1717753331, title: "ENDLESS TOUR", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "ENDLESS TOUR - Single", releaseDate: "2013-04-24" },
  { id: 1717753332, title: "Flyers!!! (MR remix)", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "ENDLESS TOUR - Single", releaseDate: "2013-04-24" },
  { id: 1718493302, title: "君との明日を願うから", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "君との明日を願うから - Single", releaseDate: "2013-04-24" },
  { id: 1718493304, title: "Flooding", artist: "クレシェンドブルー, 最上静香 (CV.田所あずさ), 北上麗花 (CV.平山笑美), 北沢志保 (CV.雨宮 天), 野々原 茜 (CV.小笠原早紀) & 箱崎星梨花 (CV.麻倉もも)", album: "君との明日を願うから - Single", releaseDate: "2013-04-24" },
  { id: 1718502616, title: "Precious Grain", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER PERFORMANCE 02 - EP", releaseDate: "2013-04-24" },
  { id: 1718502677, title: "Legend Girls!!", artist: "天海春香 (CV: 中村繪里子), 天空橋朋花 (CV.小岩井ことり), 七尾百合子 (CV.伊藤美来), 箱崎星梨花 (CV.麻倉もも) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER PERFORMANCE 02 - EP", releaseDate: "2013-04-24" },
  { id: 1718674379, title: "朝焼けのクレッシェンド", artist: "田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER LIVE THE@TER PERFORMANCE 04 - EP", releaseDate: "2013-04-24" },
  { id: 1718674382, title: "Blue Symphony", artist: "如月千早 (CV.今井麻美), 北沢志保 (CV.雨宮 天), 田中琴葉 (CV.種田梨沙) & 所 恵美 (CV.藤井ゆきよ)", album: "THE IDOLM@STER LIVE THE@TER PERFORMANCE 04 - EP", releaseDate: "2013-04-24" },
  { id: 1665511918, title: "IDOL POWER RAINBOW", artist: "天海春香、如月千早、星井美希、島村卯月、渋谷凛、本田未央、春日未来、最上静香、伊吹翼 from THE IDOLM@STER M@STERS OF IDOL WORLD!!2014", album: "IDOL POWER RAINBOW - Single", releaseDate: "2014-02-04" },
  { id: 1718502851, title: "Thank You!", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "THE IDOLM@STER LIVE THE@TER PERFORMANCE 13 - EP", releaseDate: "2014-04-30" },
  { id: 1718493352, title: "U・N・M・E・I ライブ", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "U・N・M・E・I ライブ - EP", releaseDate: "2014-06-04" },
  { id: 1718503137, title: "Shooting Stars", artist: "クレシェンドブルー, 最上静香 (CV.田所あずさ), 北上麗花 (CV.平山笑美), 北沢志保 (CV.雨宮 天), 野々原 茜 (CV.小笠原早紀) & 箱崎星梨花 (CV.麻倉もも)", album: "THE IDOLM@STER LIVE THE@TER HARMONY 03", releaseDate: "2014-09-24" },
  { id: 1718503142, title: "Catch my dream", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER HARMONY 03", releaseDate: "2014-09-24" },
  { id: 1718503143, title: "Welcome!!", artist: "クレシェンドブルー, 最上静香 (CV.田所あずさ), 北上麗花 (CV.平山笑美), 北沢志保 (CV.雨宮 天), 野々原 茜 (CV.小笠原早紀) & 箱崎星梨花 (CV.麻倉もも)", album: "THE IDOLM@STER LIVE THE@TER HARMONY 03", releaseDate: "2014-09-24" },
  { id: 1718675091, title: "ジレるハートに火をつけて", artist: "灼熱少女 (バーニングガール), 田中琴葉 (CV.種田梨沙), 大神 環 (CV.稲川英里), 高坂海美 (CV.上田麗奈), 所 恵美 (CV.藤井ゆきよ) & 宮尾美也 (CV.桐谷蝶々)", album: "THE IDOLM@STER LIVE THE@TER HARMONY 06", releaseDate: "2014-11-26" },
  { id: 1718675097, title: "ホントウノワタシ", artist: "田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER LIVE THE@TER HARMONY 06", releaseDate: "2014-11-26" },
  { id: 1718501962, title: "Dreaming!", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "THE IDOLM@STER LIVE THE@TER DREAMERS 01 Dreaming! - EP", releaseDate: "2015-09-30" },
  { id: 1718502492, title: "アライブファクター", artist: "如月千早 (CV.今井麻美) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER DREAMERS 03 - EP", releaseDate: "2015-12-02" },
  { id: 1718502638, title: "Understand? Understand!", artist: "高坂海美 (CV.上田麗奈) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER LIVE THE@TER DREAMERS 06 - EP", releaseDate: "2016-03-23" },
  { id: 1718493069, title: "ターンオンタイム!", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "ターンオンタイム! - EP", releaseDate: "2016-08-10" },
  { id: 1718726518, title: "プリムラ", artist: "ウィルゴ, 永吉 昴 (CV.斉藤佑圭), 七尾百合子 (CV.伊藤美来) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER FORWARD 02 BlueMoon Harmony - EP", releaseDate: "2017-01-11" },
  { id: 1718726521, title: "brave HARMONY", artist: "BlueMoon Harmony, 北上麗花 (CV.平山笑美), 篠宮可憐 (CV.近藤 唯), ジュリア (CV.愛美), 高山紗代子 (CV.駒形友梨), 天空橋朋花 (CV.小岩井ことり), 所 恵美 (CV.藤井ゆきよ), 永吉 昴 (CV.斉藤佑圭), 七尾百合子 (CV.伊藤美来), 二階堂千鶴 (CV.野村香菜子), 舞浜 歩 (CV.戸田めぐみ), 真壁瑞希 (CV.阿部里果) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER LIVE THE@TER FORWARD 02 BlueMoon Harmony - EP", releaseDate: "2017-01-11" },
  { id: 1718881140, title: "SING MY SONG", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE 03 - EP", releaseDate: "2017-10-25" },
  { id: 1717730208, title: "FairyTaleじゃいられない", artist: "フェアリースターズ, 最上静香 (CV.田所あずさ), 白石 紬 (CV.南 早紀), 所 恵美 (CV.藤井ゆきよ), ジュリア (CV.愛美) & 北沢志保 (CV.雨宮 天)", album: "THE IDOLM@STER MILLION THE@TER GENERATION 02 フェアリースターズ - Single", releaseDate: "2017-11-22" },
  { id: 1718493146, title: "シルエット", artist: "田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE 08 - EP", releaseDate: "2018-04-04" },
  { id: 1717753210, title: "DIAMOND DAYS", artist: "桜守歌織 (CV.香里有佐), 最上静香 (CV.田所あずさ), 望月杏奈 (CV.夏川椎菜), 百瀬莉緒 (CV.山口立花子) & 宮尾美也 (CV.桐谷蝶々)", album: "THE IDOLM@STER THE@TER BOOST 02 - Single", releaseDate: "2018-10-24" },
  { id: 1718676463, title: "オーディナリィ・クローバー", artist: "桜守歌織 (CV.香里有佐), 最上静香 (CV.田所あずさ), 望月杏奈 (CV.夏川椎菜), 百瀬莉緒 (CV.山口立花子) & 宮尾美也 (CV.桐谷蝶々)", album: "THE IDOLM@STER MILLION THE@TER BEST", releaseDate: "2018-10-24" },
  { id: 1718676464, title: "ラスト・アクトレス", artist: "田中琴葉 (CV.種田梨沙), 周防桃子 (CV.渡部恵子), 馬場このみ (CV.髙橋ミナミ), 真壁瑞希 (CV.阿部里果) & 白石 紬 (CV.南 早紀)", album: "THE IDOLM@STER MILLION THE@TER BEST", releaseDate: "2018-11-28" },
  { id: 1717730231, title: "ハーモニクス", artist: "D/Zeal, ジュリア (CV.愛美) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION THE@TER GENERATION 12 D/Zeal - Single", releaseDate: "2018-12-26" },
  { id: 1717730232, title: "餞の鳥", artist: "D/Zeal, ジュリア (CV.愛美) & 最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION THE@TER GENERATION 12 D/Zeal - Single", releaseDate: "2018-12-26" },
  { id: 1717733417, title: "Starry Melody (Brand New Ver.)", artist: "Starlight Melody, 春日未来 (CV.山崎はるか), 大神 環 (CV.稲川英里), 北沢志保 (CV.雨宮 天), 高坂海美 (CV.上田麗奈), 周防桃子 (CV.渡部恵子), 田中琴葉 (CV.種田梨沙), 徳川まつり (CV.諏訪彩花), 豊川風花 (CV.末柄里恵), 野々原 茜 (CV.小笠原早紀), 箱崎星梨花 (CV.麻倉もも), 馬場このみ (CV.髙橋ミナミ), 松田亜利沙 (CV.村川梨衣) & 宮尾美也 (CV.桐谷蝶々)", album: "Starry Melody (Brand New Ver.) - Single", releaseDate: "2019-03-13" },
  { id: 1717730196, title: "Episode. Tiara", artist: "STAR ELEMENTS, 春日未来 (CV.山崎はるか), 矢吹可奈 (CV.木戸衣吹) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION THE@TER GENERATION 17 STAR ELEMENTS - Single", releaseDate: "2019-05-29" },
  { id: 1717730197, title: "ギブミーメタファー", artist: "STAR ELEMENTS, 春日未来 (CV.山崎はるか), 矢吹可奈 (CV.木戸衣吹) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION THE@TER GENERATION 17 STAR ELEMENTS - Single", releaseDate: "2019-05-29" },
  { id: 1717753336, title: "Parade d'amour", artist: "オペラセリア・煌輝座, 北沢志保 (CV.雨宮 天), 桜守歌織 (CV.香里有佐), 徳川まつり (CV.諏訪彩花) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION THE@TER WAVE 11 オペラセリア・煌輝座 - Single", releaseDate: "2020-07-29" },
  { id: 1717753607, title: "星宙のVoyage", artist: "オペラセリア・煌輝座, 北沢志保 (CV.雨宮 天), 桜守歌織 (CV.香里有佐), 徳川まつり (CV.諏訪彩花) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION THE@TER WAVE 11 オペラセリア・煌輝座 - Single", releaseDate: "2020-09-23" },
  { id: 1718493094, title: "なんどでも笑おう (ミリオンライブ!Ver.)", artist: "MILLIONSTARS, 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "なんどでも笑おう【ミリオンライブ!盤】 - EP", releaseDate: "2020-09-30" },
  { id: 1556000499, title: "Jet to the Future (M@STER VERSION)", artist: "最上静香 (CV: 田所あずさ), ジュリア (CV: 愛美), 木村夏樹 (CV: 安野希世乃) & 多田李衣菜 (CV: 青木瑠璃子)", album: "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER COLLABORATION! ハーモニクス - EP", releaseDate: "2021-03-17" },
  { id: 1717753906, title: "ABSOLUTE RUN!!!", artist: "ストロベリーポップムーン, 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "THE IDOLM@STER MILLION THE@TER WAVE 18 ストロベリーポップムーン - Single", releaseDate: "2021-04-28" },
  { id: 1717753292, title: "リフレインキス (Brand New Ver.)", artist: "スコーピオ, 北沢志保 (CV.雨宮 天), 高坂海美 (CV.上田麗奈), 田中琴葉 (CV.種田梨沙) & 松田亜利沙 (CV.村川梨衣)", album: "リフレインキス (Brand New Ver.) - Single", releaseDate: "2021-06-10" },
  { id: 1717754117, title: "Be proud", artist: "ストロベリーポップムーン, 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "THE IDOLM@STER MILLION THE@TER WAVE 18 ストロベリーポップムーン - Single", releaseDate: "2021-06-23" },
  { id: 1717753696, title: "GR@TITUDE (ミリオンライブ!Ver.)", artist: "MILLIONSTARS, 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ), 伊吹 翼 (CV.Machico), 白石 紬 (CV.南 早紀) & 桜守歌織 (CV.香里有佐)", album: "THE IDOLM@STER STARLIT SEASON 00 GR@TITUDE【ランティス盤】 - Single", releaseDate: "2021-10-06" },
  { id: 1718903544, title: "真夏のダイヤ☆", artist: "百瀬莉緒 (CV.山口立花子), 萩原雪歩 (CV: 浅倉杏美), 田中琴葉 (CV.種田梨沙) & 双海真美 (CV: 下田麻美)", album: "THE IDOLM@STER MILLION THE@TER SEASON BRIGHT DIAMOND - EP", releaseDate: "2021-10-27" },
  { id: 1718493704, title: "THE IDOLM@STER", artist: "天海春香 (CV: 中村繪里子), 如月千早 (CV.今井麻美), 星井美希 (CV.長谷川明子), 萩原雪歩 (CV: 浅倉杏美), 高槻やよい (CV: 仁後真耶子), 秋月律子 (CV: 若林直美), 三浦あずさ (CV.たかはし智秋), 水瀬伊織 (CV.釘宮理恵), 菊地真 (CV: 平田宏美), 双海亜美 (CV: 下田麻美), 双海真美 (CV: 下田麻美), 四条貴音 (CV: 原 由実), 我那覇響 (CV: 沼倉愛美), 安部菜々 (CV: 三宅麻理恵), 神崎蘭子 (CV: 内田真礼), 城ヶ崎美嘉 (CV: 佳村はるか), 双葉杏 (CV: 五十嵐裕美), 諸星きらり (CV: 松嵜 麗), 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ), 伊吹 翼 (CV.Machico), 白石 紬 (CV.南 早紀), 桜守歌織 (CV.香里有佐), 白瀬咲耶 (CV.八巻アンナ), 小宮果穂 (CV.河野ひより), 杜野凛世 (CV.丸岡和佳奈), 大崎甘奈 (CV.黒木ほの香), 大崎甜花 (CV.前川涼子) & 奥空心白 (CV.田中あいみ)", album: "THE IDOLM@STER STARLIT SEASON 01", releaseDate: "2021-12-01" },
  { id: 1718493705, title: "お願い!シンデレラ", artist: "安部菜々 (CV: 三宅麻理恵), 神崎蘭子 (CV: 内田真礼), 城ヶ崎美嘉 (CV: 佳村はるか), 双葉杏 (CV: 五十嵐裕美), 諸星きらり (CV: 松嵜 麗), 高垣楓 (CV: 早見沙織), 春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ), 伊吹 翼 (CV.Machico), 白石 紬 (CV.南 早紀) & 桜守歌織 (CV.香里有佐)", album: "THE IDOLM@STER STARLIT SEASON 01", releaseDate: "2021-12-01" },
  { id: 1602208431, title: "Brand New Theater!", artist: "天海春香, 如月千早, 星井美希, 萩原雪歩, 高槻やよい, 秋月律子, 三浦あずさ, 水瀬伊織, 菊地真, 双海亜美, 双海真美, 四条貴音, 我那覇響, 安部菜々, 神崎蘭子, 城ヶ崎美嘉, 双葉杏, 諸星きらり, 春日未来, 最上静香, 伊吹翼, 白石紬, 桜守歌織, 田中琴葉", album: "THE IDOLM@STER STARLIT SEASON 02", releaseDate: "2022-01-19" },
  { id: 1718496910, title: "アイシテの呪縛～Je vous aime～", artist: "如月千早 (CV.今井麻美), 秋月律子 (CV: 若林直美), 三浦あずさ (CV.たかはし智秋), 四条貴音 (CV: 原 由実), 神崎蘭子 (CV: 内田真礼), 最上静香 (CV.田所あずさ), 白石 紬 (CV.南 早紀), 白瀬咲耶 (CV.八巻アンナ), 杜野凛世 (CV.丸岡和佳奈) & 奥空心白 (CV.田中あいみ)", album: "THE IDOLM@STER STARLIT SEASON 03", releaseDate: "2022-03-02" },
  { id: 1718496914, title: "READY!!", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 伊吹 翼 (CV.Machico)", album: "THE IDOLM@STER STARLIT SEASON 03", releaseDate: "2022-03-02" },
  { id: 1718493382, title: "Cross the future", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE2 05 - EP", releaseDate: "2022-03-23" },
  { id: 1618722654, title: "KAWAII ウォーズ", artist: "天海春香 (CV: 中村繪里子), 水瀬伊織 (CV.釘宮理恵), 菊地真 (CV: 平田宏美), 我那覇響 (CV: 沼倉愛美), 安部菜々 (CV: 三宅麻理恵), 双葉杏 (CV: 五十嵐裕美), 春日未来 (CV.山崎はるか), 田中琴葉 (CV.種田梨沙), 大崎甘奈 (CV.黒木ほの香), 大崎甜花 (CV.前川涼子), 奥空心白 (CV: 田中あいみ) & 詩花 (CV.高橋李依)", album: "THE IDOLM@STER STARLIT SEASON 04", releaseDate: "2022-04-13" },
  { id: 1618722655, title: "ダンス・ダンス・ダンス", artist: "如月千早 (CV.今井麻美), 秋月律子 (CV: 若林直美), 三浦あずさ (CV.たかはし智秋), 四条貴音 (CV: 原 由実), 神崎蘭子 (CV: 内田真礼), 高垣楓 (CV: 早見沙織), 最上静香 (CV: 田所あずさ), 白石紬 (CV.南 早紀), 白瀬咲耶 (CV.八巻アンナ), 杜野凛世 (CV.丸岡和佳奈), 奥空心白 (CV: 田中あいみ) & 玲音 (CV.茅原実里)", album: "THE IDOLM@STER STARLIT SEASON 04", releaseDate: "2022-04-13" },
  { id: 1718903432, title: "Criminally Dinner ～正餐とイーヴルナイフ～", artist: "星井美希 (CV.長谷川明子), 舞浜 歩 (CV.戸田めぐみ), 最上静香 (CV.田所あずさ), 篠宮可憐 (CV.近藤 唯) & 中谷 育 (CV.原嶋あかり)", album: "THE IDOLM@STER MILLION THE@TER SEASON SHADE OF SPADE - EP", releaseDate: "2022-07-30" },
  { id: 1718502090, title: "サウンド・オブ・ビギニング", artist: "田中琴葉 (CV.種田梨沙), ロコ (CV.中村温姫), 周防桃子 (CV.渡部恵子), 二階堂千鶴 (CV.野村香菜子) & 宮尾美也 (CV.桐谷蝶々)", album: "THE IDOLM@STER MILLION THE@TER SEASON FINAL - EP", releaseDate: "2022-11-26" },
  { id: 1718903272, title: "Sing a Wing Song", artist: "田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE2 10 - EP", releaseDate: "2022-11-30" },
  { id: 1665511839, title: "アイ MUST GO!", artist: "天海春香、如月千早、星井美希、島村卯月、渋谷凛、本田未央、春日未来、最上静香、伊吹翼 from THE IDOLM@STER M@STERS OF IDOL WORLD!!2015", album: "アイ MUST GO! - Single", releaseDate: "2023-01-21" },
  { id: 1728576798, title: "春風満帆スターティング", artist: "萩原雪歩 (CV: 浅倉杏美), 福田のり子 (CV.浜崎奈々), 菊地真 (CV: 平田宏美), 最上静香 (CV.田所あずさ) & 永吉 昴 (CV.斉藤佑圭)", album: "THE IDOLM@STER MILLION THE@TER VARIETY 03 - EP", releaseDate: "2023-03-28" },
  { id: 1718501860, title: "SECOND LIVINGROOM", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "SECOND LIVINGROOM - EP", releaseDate: "2023-03-29" },
  { id: 1735684886, title: "ミステイク・マーダー!", artist: "田中琴葉 (CV.種田梨沙), 豊川風花 (CV.末柄里恵), 春日未来 (CV.山崎はるか), 北沢志保 (CV.雨宮 天) & 七尾百合子 (CV.伊藤美来)", album: "THE IDOLM@STER MILLION C@STING 03 ミステイク・マーダー! - Single", releaseDate: "2024-01-28" },
  { id: 1729566155, title: "We Have A Dream (Anime ver.)", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ), 伊吹 翼 (CV.Machico), 徳川まつり (CV.諏訪彩花), 七尾百合子 (CV.伊藤美来), 箱崎星梨花 (CV.麻倉もも) & 望月杏奈 (CV.夏川椎菜)", album: "THE IDOLM@STER MILLION ANIMATION THE@TER START THE DREAM", releaseDate: "2024-02-21" },
  { id: 1729566157, title: "Snow White", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION ANIMATION THE@TER START THE DREAM", releaseDate: "2024-02-21" },
  { id: 1729566159, title: "G線上のアリア", artist: "如月千早 (CV.今井麻美), 最上静香 (CV.田所あずさ), 北沢志保 (CV.雨宮 天) & 箱崎星梨花 (CV.麻倉もも)", album: "THE IDOLM@STER MILLION ANIMATION THE@TER START THE DREAM", releaseDate: "2024-02-21" },
  { id: 1729566160, title: "Gift Sign", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION ANIMATION THE@TER START THE DREAM", releaseDate: "2024-02-21" },
  { id: 1740697076, title: "銀のテーブル木苺ジャム", artist: "水瀬伊織 (CV.釘宮理恵), 最上静香 (CV.田所あずさ), 菊地真 (CV: 平田宏美), 松田亜利沙 (CV.村川梨衣) & 矢吹可奈 (CV.木戸衣吹)", album: "THE IDOLM@STER MILLION C@STING 04 銀のテーブル木苺ジャム - Single", releaseDate: "2024-02-26" },
  { id: 1735684710, title: "さんぶんのいち", artist: "春日未来 (CV.山崎はるか), 最上静香 (CV.田所あずさ) & 箱崎星梨花 (CV.麻倉もも)", album: "さんぶんのいち - EP", releaseDate: "2024-03-27" },
  { id: 1758060554, title: "推しってほんと", artist: "所 恵美 (CV.藤井ゆきよ), 島原エレナ (CV.角元明日香), 佐竹美奈子 (CV.大関英里), 田中琴葉 (CV.種田梨沙) & 矢吹可奈 (CV.木戸衣吹)", album: "推しってほんと - Single", releaseDate: "2024-08-27" },
  { id: 1792108939, title: "I.V.", artist: "真壁瑞希 (CV.阿部里果), 七尾百合子 (CV.伊藤美来), 最上静香 (CV.田所あずさ), 百瀬莉緒 (CV.山口立花子) & ロコ (CV.中村温姫)", album: "I.V. - Single", releaseDate: "2025-02-26" },
  { id: 1798441808, title: "Bestest!!", artist: "馬場このみ (CV.髙橋ミナミ), 天海春香 (CV: 中村繪里子), 田中琴葉 (CV.種田梨沙), 中谷 育 (CV.原嶋あかり) & 松田亜利沙 (CV.村川梨衣)", album: "Bestest!! - Single", releaseDate: "2025-03-28" },
  { id: 1805091930, title: "頂上決戦ヴィクトリー!!!!!!", artist: "最上静香 (CV.田所あずさ), 菊地真 (CV: 平田宏美), エミリー スチュアート (CV.郁原ゆう), 大神 環 (CV.稲川英里), 北上麗花 (CV.平山笑美) & 天空橋朋花 (CV.小岩井ことり)", album: "頂上決戦ヴィクトリー!!!!!! - Single", releaseDate: "2025-04-27" },
  { id: 1823809087, title: "スペードのQ (ぴえぴえ ver.)", artist: "箱崎星梨花 (CV.麻倉もも) & 田中琴葉 (CV.種田梨沙)", album: "THE IDOLM@STER MILLION LIVE! 蝶々むすび - EP", releaseDate: "2025-07-30" },
  { id: 6776256642, title: "UNION!! (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256644, title: "Glow Map (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256647, title: "Harmony 4 You (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256648, title: "夢にかけるRainbow (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256649, title: "Crossing! (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256650, title: "グッドサイン (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 6776256651, title: "7Days A Week!! (最上静香 Ver.)", artist: "最上静香 (CV.田所あずさ)", album: "THE IDOLM@STER MILLION LIVE! SPECIAL SOLO RECORDS 最上静香", releaseDate: "2025-10-01" },
  { id: 1879989268, title: "Prima Princess!!", artist: "松田亜利沙 (CV.村川梨衣), エミリー スチュアート (CV.郁原ゆう), 高坂海美 (CV.上田麗奈), 佐竹美奈子 (CV.大関英里) & 田中琴葉 (CV.種田梨沙)", album: "Prima Princess!! - Single", releaseDate: "2026-03-28" },
  { id: 6810503706, title: "ホントウノワタシ(Night 第2幕「BRILLIANT STAGE」より)-Live", artist: "田中琴葉 (CV.種田梨沙), 東京フィルハーモニー交響楽団, THE IDOLM@STER Series & Bandai Namco Game Music", album: "THE IDOLM@STER 20th anniversary ORCHESTRA CONCERT SYMPHONY OF BRILLIANT STARS コンサートアルバム", releaseDate: "2026-09-16" },
] satisfies SongQuizSong[];
